# Tarea Calificada 3

## Parte 1

In [256]:
import pandas as pd

In [259]:
# Definir la ruta de los archivos en GitHub
append_data_path = 'https://github.com/Jampier1JO/ProyectosPUCP/raw/0a1168b80b6da553a2fa8c20d6575cf78c53131f/TareaCalificada3'

In [260]:
#Leemos el primer archivo de excel Level1
level1=pd.read_excel(append_data_path+"/level1.xlsx")

In [261]:
level1

,Unnamed: 0,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
4,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,62,Malaysia,0.803,NaN,74.8839,NaN,13.34304,NaN,10.64506,NaN,26657.94355,NaN,-8,NaN,61,VERY HIGH HUMAN DEVELOPMENT
68,63,Georgia,0.802,NaN,71.694,NaN,15.56852,NaN,12.82222,NaN,14664.16825,NaN,17,NaN,64,VERY HIGH HUMAN DEVELOPMENT
69,63,Mauritius,0.802,NaN,73.5552,NaN,15.17353,e,10.42791,e,22025.34631,NaN,-1,NaN,62,VERY HIGH HUMAN DEVELOPMENT
70,63,Serbia,0.802,NaN,74.1923,NaN,14.40009,NaN,11.36987,NaN,19123.02747,NaN,4,NaN,62,VERY HIGH HUMAN DEVELOPMENT
71,66,Thailand,0.8,NaN,78.7154,NaN,15.882219,m,8.69712,NaN,17030.15352,NaN,6,NaN,64,VERY HIGH HUMAN DEVELOPMENT

In [262]:
#Verificamos si hay columnas con valores nulos
level1[level1.isnull().all(axis=1)]

,Unnamed: 0,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [263]:
#Tomaremos todo el contenido excepto las filas nulas
level1=level1[~level1.isnull().all(axis=1)]
level1.reset_index(drop=True,inplace=True)
level1

,Unnamed: 0,Table 1. Human Development Index and its components,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,SDG3,NaN,SDG4.3,NaN,SDG4.4,NaN,SDG8.5,NaN,NaN,NaN,NaN,NaN
1,HDI rank,Country,Human Development Index (HDI),NaN,Life expectancy at birth,NaN,Expected years of schooling,NaN,Mean years of schooling,NaN,Gross national income (GNI) per capita,NaN,GNI per capita rank minus HDI rank,NaN,HDI rank,NaN
2,NaN,NaN,Value,NaN,(years),NaN,(years),NaN,(years),NaN,(2017 PPP $),NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,2021,NaN,2021,NaN,2021,a,2021,a,2021,NaN,2021,b,2020,NaN
4,1,Switzerland,0.962,NaN,83.9872,NaN,16.500299,NaN,13.85966,NaN,66933.00454,NaN,5,NaN,3,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,62,Malaysia,0.803,NaN,74.8839,NaN,13.34304,NaN,10.64506,NaN,26657.94355,NaN,-8,NaN,61,VERY HIGH HUMAN DEVELOPMENT
66,63,Georgia,0.802,NaN,71.694,NaN,15.56852,NaN,12.82222,NaN,14664.16825,NaN,17,NaN,64,VERY HIGH HUMAN DEVELOPMENT
67,63,Mauritius,0.802,NaN,73.5552,NaN,15.17353,e,10.42791,e,22025.34631,NaN,-1,NaN,62,VERY HIGH HUMAN DEVELOPMENT
68,63,Serbia,0.802,NaN,74.1923,NaN,14.40009,NaN,11.36987,NaN,19123.02747,NaN,4,NaN,62,VERY HIGH HUMAN DEVELOPMENT
69,66,Thailand,0.8,NaN,78.7154,NaN,15.882219,m,8.69712,NaN,17030.15352,NaN,6,NaN,64,VERY HIGH HUMAN DEVELOPMENT

In [264]:
#Analizando las cabeceras de las columnas notamos un patron y buscamos la forma de limpiar dichas cabeceras
[a for a in zip(level1.iloc[1,:],level1.iloc[2,:],level1.iloc[3,:])]

[('HDI rank', nan, nan),
 ('Country', nan, nan),
 ('Human Development Index (HDI) ', 'Value', 2021),
 (nan, nan, nan),
 ('Life expectancy at birth', '(years)', 2021),
 (nan, nan, nan),
 ('Expected years of schooling', '(years)', 2021),
 (nan, nan, 'a'),
 ('Mean years of schooling', '(years)', 2021),
 (nan, nan, 'a'),
 ('Gross national income (GNI) per capita', '(2017 PPP $)', 2021),
 (nan, nan, nan),
 ('GNI per capita rank minus HDI rank', nan, 2021),
 (nan, nan, 'b'),
 ('HDI rank', nan, 2020),
 (nan, nan, nan)]

In [265]:
#Juntamos los elementos de la serie en una cadena eliminando la coma que lo separaba
[''.join(map(str, pd.Series(a).dropna())) for a in zip(level1.iloc[1,:], level1.iloc[2,:], level1.iloc[3,:])]

['HDI rank',
 'Country',
 'Human Development Index (HDI) Value2021',
 '',
 'Life expectancy at birth(years)2021',
 '',
 'Expected years of schooling(years)2021',
 'a',
 'Mean years of schooling(years)2021',
 'a',
 'Gross national income (GNI) per capita(2017 PPP $)2021',
 '',
 'GNI per capita rank minus HDI rank2021',
 'b',
 'HDI rank2020',
 '']

In [266]:
#Modifico las columnas con la serie de textos hallados anteriormente
level1.columns = [''.join(map(str, pd.Series(a).dropna())) for a in zip(level1.iloc[1, :], level1.iloc[2, :], level1.iloc[3, :])]
#Renombro la columna por comodidades
level1 = level1.rename(columns={'Human Development Index (HDI) Value2021': 'Human Development Index (HDI) 2021'})

In [267]:
#Visualizo mis nuevas columnas
level1.columns

Index(['HDI rank', 'Country', 'Human Development Index (HDI) 2021', '',
       'Life expectancy at birth(years)2021', '',
       'Expected years of schooling(years)2021', 'a',
       'Mean years of schooling(years)2021', 'a',
       'Gross national income (GNI) per capita(2017 PPP $)2021', '',
       'GNI per capita rank minus HDI rank2021', 'b', 'HDI rank2020', ''],
      dtype='object')

In [268]:
#Quiero apreciar cuales son las columnas NO vacÃ­as
[a for a in level1.columns if len(a)>2]

['HDI rank',
 'Country',
 'Human Development Index (HDI) 2021',
 'Life expectancy at birth(years)2021',
 'Expected years of schooling(years)2021',
 'Mean years of schooling(years)2021',
 'Gross national income (GNI) per capita(2017 PPP $)2021',
 'GNI per capita rank minus HDI rank2021',
 'HDI rank2020']

In [269]:
#Me quedo solo con las columnas con cabeceras NO vacÃ­as, lo actualizo
level1=level1[[a for a in level1.columns if len(a)>2]]
level1.head(10)

,HDI rank,Country,Human Development Index (HDI) 2021,Life expectancy at birth(years)2021,Expected years of schooling(years)2021,Mean years of schooling(years)2021,Gross national income (GNI) per capita(2017 PPP $)2021,GNI per capita rank minus HDI rank2021,HDI rank2020
0,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
1,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
2,NaN,NaN,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
3,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
4,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
5,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
6,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
7,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
8,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,5
9,6,Denmark,0.948,81.3753,18.7148,12.96049,60364.78595,6,5

In [270]:
#visualizo las columnas
level1.columns

Index(['HDI rank', 'Country', 'Human Development Index (HDI) 2021',
       'Life expectancy at birth(years)2021',
       'Expected years of schooling(years)2021',
       'Mean years of schooling(years)2021',
       'Gross national income (GNI) per capita(2017 PPP $)2021',
       'GNI per capita rank minus HDI rank2021', 'HDI rank2020'],
      dtype='object')

In [271]:
#Visualizamos el reemplazo los parentesis y espacios por "_"
level1.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)

Index(['Hdi_Rank', 'Country', 'Human_Development_Index__2021',
       'Life_Expectancy_At_Birth2021', 'Expected_Years_Of_Schooling2021',
       'Mean_Years_Of_Schooling2021', 'Gross_National_Income__Per_Capita2021',
       'Gni_Per_Capita_Rank_Minus_Hdi_Rank2021', 'Hdi_Rank2020'],
      dtype='object')

In [272]:
#Reemplazamos los parentesis y espacios por "_"
level1.columns=level1.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)
level1

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
1,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
2,NaN,NaN,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
3,NaN,NaN,2021,2021,2021,2021,2021,2021,2020
4,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
...,...,...,...,...,...,...,...,...,...
65,62,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355,-8,61
66,63,Georgia,0.802,71.694,15.56852,12.82222,14664.16825,17,64
67,63,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631,-1,62
68,63,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747,4,62
69,66,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352,6,64

In [273]:
#Hacemos una copia del df y analizamos la existencia de valores nulos
level1_better=level1.copy()
level1_better.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                67 non-null     object
 1   Country                                 67 non-null     object
 2   Human_Development_Index__2021           69 non-null     object
 3   Life_Expectancy_At_Birth2021            70 non-null     object
 4   Expected_Years_Of_Schooling2021         70 non-null     object
 5   Mean_Years_Of_Schooling2021             70 non-null     object
 6   Gross_National_Income__Per_Capita2021   70 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  68 non-null     object
 8   Hdi_Rank2020                            68 non-null     object
dtypes: object(9)
memory usage: 5.1+ KB

In [274]:
#Analizamos los valores nulos en la columna "Country"
level1_better[level1_better.Country.isnull()]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,NaN,NaN,NaN,SDG3,SDG4.3,SDG4.4,SDG8.5,NaN,NaN
2,NaN,NaN,Value,(years),(years),(years),(2017 PPP $),NaN,NaN
3,NaN,NaN,2021,2021,2021,2021,2021,2021,2020

In [275]:
#Eliminamos las filas con valores nulos en "Country"
level1_better=level1_better[~level1_better.Country.isnull()]
level1_better.reset_index(drop=True, inplace=True)
level1_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank
1,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
2,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
3,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
4,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
...,...,...,...,...,...,...,...,...,...
62,62,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355,-8,61
63,63,Georgia,0.802,71.694,15.56852,12.82222,14664.16825,17,64
64,63,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631,-1,62
65,63,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747,4,62
66,66,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352,6,64

In [276]:
#Buscamos valores NO numericos de una fila
level1_better[level1_better.iloc[:, 2].str.contains('\D+').fillna(False)]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank

In [277]:
#Eliminamos la fila de cadenas
level1_better=level1_better[~level1_better.iloc[:, 2].str.contains('\D+').fillna(False)]
level1_better.reset_index(drop=True, inplace=True)
level1_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,1,Switzerland,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
1,2,Norway,0.961,83.2339,18.1852,13.00363,64660.10622,6,1
2,3,Iceland,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
3,4,"Hong Kong, China (SAR)",0.952,85.4734,17.27817,12.22621,62606.8454,6,4
4,5,Australia,0.951,84.5265,21.05459,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
61,62,Malaysia,0.803,74.8839,13.34304,10.64506,26657.94355,-8,61
62,63,Georgia,0.802,71.694,15.56852,12.82222,14664.16825,17,64
63,63,Mauritius,0.802,73.5552,15.17353,10.42791,22025.34631,-1,62
64,63,Serbia,0.802,74.1923,14.40009,11.36987,19123.02747,4,62
65,66,Thailand,0.8,78.7154,15.882219,8.69712,17030.15352,6,64

In [278]:
#Probar si existen valores nulos en la columna "Hdi_Rank"
level1_better[level1_better.Hdi_Rank.isnull()]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [279]:
#Ahora validando si existe alguna columna nula
level1_better[level1_better.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [280]:
#Validamos la calidad de nuestros datos
level1_better.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                66 non-null     object
 1   Country                                 66 non-null     object
 2   Human_Development_Index__2021           66 non-null     object
 3   Life_Expectancy_At_Birth2021            66 non-null     object
 4   Expected_Years_Of_Schooling2021         66 non-null     object
 5   Mean_Years_Of_Schooling2021             66 non-null     object
 6   Gross_National_Income__Per_Capita2021   66 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  66 non-null     object
 8   Hdi_Rank2020                            66 non-null     object
dtypes: object(9)
memory usage: 4.8+ KB

In [281]:
#Evaluamos si los elementos de la columna "Gross_National_Income__Per_Capita2021" son cadenas o textos
level1_better.iloc[:,6]

0     66933.00454
1     64660.10622
2     55782.04981
3      62606.8454
4     49238.43335
         ...
61    26657.94355
62    14664.16825
63    22025.34631
64    19123.02747
65    17030.15352
Name: Gross_National_Income__Per_Capita2021, Length: 66, dtype: object

In [282]:
#Vamos a transformar todas las columnas en numericos sin afectar a la columna "Country"
level1_clean=level1_better.set_index('Country')
level1_formatted=level1_clean.apply(pd.to_numeric)
level1_formatted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 66 entries, Switzerland to Thailand
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                66 non-null     int64
 1   Human_Development_Index__2021           66 non-null     float64
 2   Life_Expectancy_At_Birth2021            66 non-null     float64
 3   Expected_Years_Of_Schooling2021         66 non-null     float64
 4   Mean_Years_Of_Schooling2021             66 non-null     float64
 5   Gross_National_Income__Per_Capita2021   66 non-null     float64
 6   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  66 non-null     int64
 7   Hdi_Rank2020                            66 non-null     int64
dtypes: float64(5), int64(3)
memory usage: 4.6+ KB

In [283]:
#Devolvemos del indice a la columna "Country"
level1_formatted.reset_index(drop=False,inplace=True)
level1_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,Switzerland,1,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
1,Norway,2,0.961,83.2339,18.185200,13.00363,64660.10622,6,1
2,Iceland,3,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
3,"Hong Kong, China (SAR)",4,0.952,85.4734,17.278170,12.22621,62606.84540,6,4
4,Australia,5,0.951,84.5265,21.054590,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
61,Malaysia,62,0.803,74.8839,13.343040,10.64506,26657.94355,-8,61
62,Georgia,63,0.802,71.6940,15.568520,12.82222,14664.16825,17,64
63,Mauritius,63,0.802,73.5552,15.173530,10.42791,22025.34631,-1,62
64,Serbia,63,0.802,74.1923,14.400090,11.36987,19123.02747,4,62
65,Thailand,66,0.800,78.7154,15.882219,8.69712,17030.15352,6,64

In [284]:
#Colocamos en mayuscula los elementos de la columna "Country"
level1_formatted['Country']=level1_formatted.Country.str.strip()
level1_formatted['Country']=level1_formatted.Country.str.upper()
level1_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.85966,66933.00454,5,3
1,NORWAY,2,0.961,83.2339,18.185200,13.00363,64660.10622,6,1
2,ICELAND,3,0.959,82.6782,19.163059,13.76717,55782.04981,11,2
3,"HONG KONG, CHINA (SAR)",4,0.952,85.4734,17.278170,12.22621,62606.84540,6,4
4,AUSTRALIA,5,0.951,84.5265,21.054590,12.72682,49238.43335,18,5
...,...,...,...,...,...,...,...,...,...
61,MALAYSIA,62,0.803,74.8839,13.343040,10.64506,26657.94355,-8,61
62,GEORGIA,63,0.802,71.6940,15.568520,12.82222,14664.16825,17,64
63,MAURITIUS,63,0.802,73.5552,15.173530,10.42791,22025.34631,-1,62
64,SERBIA,63,0.802,74.1923,14.400090,11.36987,19123.02747,4,62
65,THAILAND,66,0.800,78.7154,15.882219,8.69712,17030.15352,6,64

In [285]:
#Agregamos la columna de indicador de desarrollo
level1_formatted['Development'] = "VERY HIGH HUMAN DEVELOPMENT"
level1_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.85966,66933.00454,5,3,VERY HIGH HUMAN DEVELOPMENT
1,NORWAY,2,0.961,83.2339,18.185200,13.00363,64660.10622,6,1,VERY HIGH HUMAN DEVELOPMENT
2,ICELAND,3,0.959,82.6782,19.163059,13.76717,55782.04981,11,2,VERY HIGH HUMAN DEVELOPMENT
3,"HONG KONG, CHINA (SAR)",4,0.952,85.4734,17.278170,12.22621,62606.84540,6,4,VERY HIGH HUMAN DEVELOPMENT
4,AUSTRALIA,5,0.951,84.5265,21.054590,12.72682,49238.43335,18,5,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
61,MALAYSIA,62,0.803,74.8839,13.343040,10.64506,26657.94355,-8,61,VERY HIGH HUMAN DEVELOPMENT
62,GEORGIA,63,0.802,71.6940,15.568520,12.82222,14664.16825,17,64,VERY HIGH HUMAN DEVELOPMENT
63,MAURITIUS,63,0.802,73.5552,15.173530,10.42791,22025.34631,-1,62,VERY HIGH HUMAN DEVELOPMENT
64,SERBIA,63,0.802,74.1923,14.400090,11.36987,19123.02747,4,62,VERY HIGH HUMAN DEVELOPMENT
65,THAILAND,66,0.800,78.7154,15.882219,8.69712,17030.15352,6,64,VERY HIGH HUMAN DEVELOPMENT

In [286]:
#Leemos el segundo archivo de excel Level2
level2=pd.read_excel(append_data_path+"/level2.xlsx")

In [287]:
level2

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Unnamed: 6,Gross national income (GNI) per capita,Unnamed: 8,GNI per capita rank minus HDI rank,Unnamed: 10,HDI rank.1
0,NaN,NaN,2021.000,2021.0000,2021.000000,2021.000000,a,2021.000000,NaN,2021.0,b,2020.0
1,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67.0,Albania,0.796,76.4626,14.448000,11.286455,e,14131.110390,NaN,17.0,NaN,68.0
3,68.0,Bulgaria,0.795,71.7980,13.897290,11.413180,NaN,23078.955950,NaN,-8.0,NaN,64.0
4,68.0,Grenada,0.795,74.9362,18.662020,9.032104,l,13483.577400,NaN,18.0,NaN,70.0
5,70.0,Barbados,0.790,77.5714,15.713385,9.852701,n,12306.341000,NaN,26.0,NaN,71.0
6,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,j,16792.365950,NaN,2.0,NaN,71.0
7,72.0,Seychelles,0.785,71.2945,13.941610,10.283120,NaN,25830.617750,NaN,-17.0,NaN,69.0
8,73.0,Sri Lanka,0.782,76.3991,14.139905,10.827300,NaN,12578.220550,NaN,21.0,NaN,75.0
9,74.0,Bosnia and Herzegovina,0.780,75.3003,13.800000,10.536320,NaN,15241.914650,NaN,4.0,NaN,73.0
10,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,l,23358.332120,NaN,-16.0,NaN,76.0
11,76.0,Iran (Islamic Republic of),0.774,73.8749,14.615250,10.636453,e,13000.711700,NaN,15.0,NaN,77.0
12,77.0,Ukraine,0.773,71.6240,14.956569,11.131420,n,13255.509770,NaN,11.0,NaN,78.0
13,78.0,North Macedonia,0.770,73.8415,13.624432,10.228150,NaN,15917.752830,NaN,-3.0,NaN,79.0
14,79.0,China,0.768,78.2107,14.236115,7.600118,n,17504.399690,NaN,-8.0,NaN,82.0
15,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,o,17989.600370,NaN,-11.0,NaN,82.0
16,80.0,Moldova (Republic of),0.767,68.8459,14.433000,11.821590,NaN,14875.331890,NaN,-1.0,NaN,81.0
17,80.0,Palau,0.767,66.0204,15.784320,12.491430,p,13818.678690,NaN,5.0,NaN,80.0
18,83.0,Cuba,0.764,73.6829,14.443060,12.497734,e,7878.847482,q,37.0,NaN,73.0
19,84.0,Peru,0.762,72.3769,15.387734,9.885519,e,12245.893660,NaN,13.0,NaN,85.0
20,85.0,Armenia,0.759,72.0431,13.116760,11.330300,NaN,13157.993900,NaN,4.0,NaN,87.0
21,86.0,Mexico,0.758,70.2127,14.864440,9.221050,NaN,17896.294980,NaN,-16.0,NaN,88.0
22,87.0,Brazil,0.754,72.7504,15.599060,8.128814,e,14369.888480,NaN,-5.0,NaN,86.0
23,88.0,Colombia,0.752,72.8296,14.442750,8.862860,NaN,14384.356660,NaN,-7.0,NaN,88.0
24,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.833430,NaN,11961.087920,NaN,11.0,NaN,82.0
25,90.0,Maldives,0.747,79.9182,12.635610,7.322000,NaN,15448.127880,NaN,-14.0,NaN,97.0
26,91.0,Algeria,0.745,76.3767,14.626896,8.069284,e,10800.225460,NaN,13.0,NaN,96.0
27,91.0,Azerbaijan,0.745,69.3658,13.496890,10.542970,NaN,14256.744560,NaN,-8.0,NaN,100.0
28,91.0,Tonga,0.745,70.9857,16.048571,11.392594,n,6822.031250,NaN,34.0,NaN,90.0
29,91.0,Turkmenistan,0.745,69.2644,13.210400,11.261390,NaN,13020.715500,NaN,-1.0,NaN,93.0
30,95.0,Ecuador,0.740,73.6700,14.624230,8.817120,NaN,10311.632730,NaN,11.0,NaN,99.0
31,96.0,Mongolia,0.739,70.9754,14.980350,9.423700,NaN,10588.225320,NaN,9.0,NaN,90.0
32,97.0,Egypt,0.731,70.2207,13.786500,9.573026,e,11731.690560,NaN,4.0,NaN,97.0
33,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,e,10257.544770,NaN,10.0,NaN,94.0
34,99.0,Fiji,0.730,67.1140,14.736790,10.921548,e,9980.110866,NaN,9.0,NaN,94.0
35,99.0,Suriname,0.730,70.2743,13.035644,9.776801,m,12672.200330,NaN,-6.0,NaN,92.0
36,101.0,Uzbekistan,0.727,70.8616,12.477140,11.895590,NaN,7916.785725,NaN,18.0,NaN,107.0
37,102.0,Dominica,0.720,72.8140,13.319186,8.142186,j,11487.624220,NaN,0.0,NaN,106.0
38,102.0,Jordan,0.720,74.2563,10.646560,10.446680,NaN,9923.714974,NaN,8.0,NaN,104.0
39,104.0,Libya,0.718,71.9112,12.854280,7.599985,r,15335.712000,NaN,-27.0,NaN,117.0
40,105.0,Paraguay,0.717,70.2617,12.987991,8.861840,NaN,12349.286000,NaN,-10.0,NaN,100.0
41,106.0,"Palestine, State of",0.715,73.4727,13.358010,9.938480,NaN,6582.899416,NaN,21.0,NaN,109.0
42,106.0,Saint Lucia,0.715,71.1114,12.866110,8.545040,NaN,12048.303810,NaN,-7.0,NaN,104.0
43,108.0,Guyana,0.714,65.6734,12.502722,8.617477,NaN,22464.657340,NaN,-47.0,NaN,107.0
44,109.0,South Africa,0.713,62.3410,13.643710,11.373160,NaN,12948.373250,NaN,-17.0,NaN,102.0
45,110.0,Jamaica,0.709,70.5003,13.404920,9.154629,e,8834.475670,NaN,4.0,NaN,110.0
46,111.0,Samoa,0.707,72.7675,12.418859,11.403800,NaN,5307.953374,NaN,24.0,NaN,112.0
47,112.0,Gabon,0.706,65.8210,12.977310,9.436000,NaN,13366.934550,NaN,-25.0,NaN,113.0
48,112.0,Lebanon,0.706,75.0472,11.285870,8.718636,l,9525.831467,NaN,-1.0,NaN,103.0
49,114.0,Indonesia,0.705,67.5703,13.748894,8.556510,NaN,11466.068360,NaN,-11.0,NaN,116.0
50,115.0,Viet Nam,0.703,73.6181,12.951932,8.370280,NaN,7867.371345,NaN,6.0,NaN,113.0

In [288]:
#Analizamos la tabla y notamos que las cabeceras "Unnamed" no aportan informacion
level2 = level2.loc[:, ~level2.columns.str.startswith('Unnamed')]

In [289]:
#Verificamos si hay columnas con valores nulos
level2[level2.isnull().all(axis=1)]

Empty DataFrame
Columns: [HDI rank, Country, Human Development Index (HDI) , Life expectancy at birth, Expected years of schooling, Mean years of schooling, Gross national income (GNI) per capita, GNI per capita rank minus HDI rank, HDI rank.1]
Index: []

In [290]:
#Convertir las cabeceras en la primera fila
level2.loc[-1] = level2.columns  # AÃ±adir las cabeceras como la primera fila
level2.index = level2.index + 1  # Desplazar los Ã­ndices hacia abajo
level2 = level2.sort_index()  # Ordenar por Ã­ndice

#Eliminar las cabeceras
level2.columns = range(level2.shape[1])
level2

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4620\870654628.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  level2.loc[-1] = level2.columns  # AÃ±adir las cabeceras como la primera fila

,0,1,2,3,4,5,6,7,8
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,67.0,Albania,0.796,76.4626,14.448,11.286455,14131.11039,17.0,68.0
4,68.0,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595,-8.0,64.0
5,68.0,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774,18.0,70.0
6,70.0,Barbados,0.79,77.5714,15.713385,9.852701,12306.341,26.0,71.0
7,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595,2.0,71.0
8,72.0,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775,-17.0,69.0
9,73.0,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055,21.0,75.0
10,74.0,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465,4.0,73.0
11,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212,-16.0,76.0
12,76.0,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117,15.0,77.0
13,77.0,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977,11.0,78.0
14,78.0,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283,-3.0,79.0
15,79.0,China,0.768,78.2107,14.236115,7.600118,17504.39969,-8.0,82.0
16,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037,-11.0,82.0
17,80.0,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189,-1.0,81.0
18,80.0,Palau,0.767,66.0204,15.78432,12.49143,13818.67869,5.0,80.0
19,83.0,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482,37.0,73.0
20,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.89366,13.0,85.0
21,85.0,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939,4.0,87.0
22,86.0,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498,-16.0,88.0
23,87.0,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848,-5.0,86.0
24,88.0,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666,-7.0,88.0
25,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792,11.0,82.0
26,90.0,Maldives,0.747,79.9182,12.63561,7.322,15448.12788,-14.0,97.0
27,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546,13.0,96.0
28,91.0,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456,-8.0,100.0
29,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125,34.0,90.0
30,91.0,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155,-1.0,93.0
31,95.0,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273,11.0,99.0
32,96.0,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532,9.0,90.0
33,97.0,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056,4.0,97.0
34,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477,10.0,94.0
35,99.0,Fiji,0.73,67.114,14.73679,10.921548,9980.110866,9.0,94.0
36,99.0,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033,-6.0,92.0
37,101.0,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725,18.0,107.0
38,102.0,Dominica,0.72,72.814,13.319186,8.142186,11487.62422,0.0,106.0
39,102.0,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974,8.0,104.0
40,104.0,Libya,0.718,71.9112,12.85428,7.599985,15335.712,-27.0,117.0
41,105.0,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286,-10.0,100.0
42,106.0,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416,21.0,109.0
43,106.0,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381,-7.0,104.0
44,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734,-47.0,107.0
45,109.0,South Africa,0.713,62.341,13.64371,11.37316,12948.37325,-17.0,102.0
46,110.0,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567,4.0,110.0
47,111.0,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374,24.0,112.0
48,112.0,Gabon,0.706,65.821,12.97731,9.436,13366.93455,-25.0,113.0
49,112.0,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467,-1.0,103.0
50,114.0,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836,-11.0,116.0
51,115.0,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345,6.0,113.0

In [291]:
#Analizando las cabeceras de las columnas notamos un patron y buscamos la forma de limpiar dichas cabeceras
[a for a in zip(level2.iloc[0,:],level2.iloc[1,:])]

[('HDI rank', nan),
 ('Country', nan),
 ('Human Development Index (HDI) ', 2021.0),
 ('Life expectancy at birth', 2021.0),
 ('Expected years of schooling', 2021.0),
 ('Mean years of schooling', 2021.0),
 ('Gross national income (GNI) per capita', 2021.0),
 ('GNI per capita rank minus HDI rank', 2021.0),
 ('HDI rank.1', 2020.0)]

In [292]:
#Juntamos los elementos de la serie en una cadena eliminando la coma que lo separaba
[''.join(map(lambda x: str(int(x)) if pd.notnull(x) and isinstance(x, float) and x.is_integer() else str(x), pd.Series(a).dropna())) for a in zip(level2.iloc[0,:], level2.iloc[1,:])]

['HDI rank',
 'Country',
 'Human Development Index (HDI) 2021',
 'Life expectancy at birth2021',
 'Expected years of schooling2021',
 'Mean years of schooling2021',
 'Gross national income (GNI) per capita2021',
 'GNI per capita rank minus HDI rank2021',
 'HDI rank.12020']

In [293]:
#Modifico las columnas con la serie de textos hallados anteriormente
level2.columns = [''.join(map(lambda x: str(int(x)) if pd.notnull(x) and isinstance(x, float) and x.is_integer() else str(x), pd.Series(a).dropna())) for a in zip(level2.iloc[0,:], level2.iloc[1,:])]
#Renombro la columna por comodidades
level2 = level2.rename(columns={'HDI rank.12020': 'HDI rank2020'})

In [294]:
#Visualizo mis nuevas columnas
level2.columns

Index(['HDI rank', 'Country', 'Human Development Index (HDI) 2021',
       'Life expectancy at birth2021', 'Expected years of schooling2021',
       'Mean years of schooling2021',
       'Gross national income (GNI) per capita2021',
       'GNI per capita rank minus HDI rank2021', 'HDI rank2020'],
      dtype='object')

In [296]:
#Visualizamos el reemplazo los parentesis y espacios por "_"
level2.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)

Index(['Hdi_Rank', 'Country', 'Human_Development_Index__2021',
       'Life_Expectancy_At_Birth2021', 'Expected_Years_Of_Schooling2021',
       'Mean_Years_Of_Schooling2021', 'Gross_National_Income__Per_Capita2021',
       'Gni_Per_Capita_Rank_Minus_Hdi_Rank2021', 'Hdi_Rank2020'],
      dtype='object')

In [297]:
#Reemplazamos los parentesis y espacios por "_"
level2.columns=level2.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)
level2

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,67.0,Albania,0.796,76.4626,14.448,11.286455,14131.11039,17.0,68.0
4,68.0,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595,-8.0,64.0
5,68.0,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774,18.0,70.0
6,70.0,Barbados,0.79,77.5714,15.713385,9.852701,12306.341,26.0,71.0
7,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595,2.0,71.0
8,72.0,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775,-17.0,69.0
9,73.0,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055,21.0,75.0
10,74.0,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465,4.0,73.0
11,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212,-16.0,76.0
12,76.0,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117,15.0,77.0
13,77.0,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977,11.0,78.0
14,78.0,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283,-3.0,79.0
15,79.0,China,0.768,78.2107,14.236115,7.600118,17504.39969,-8.0,82.0
16,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037,-11.0,82.0
17,80.0,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189,-1.0,81.0
18,80.0,Palau,0.767,66.0204,15.78432,12.49143,13818.67869,5.0,80.0
19,83.0,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482,37.0,73.0
20,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.89366,13.0,85.0
21,85.0,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939,4.0,87.0
22,86.0,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498,-16.0,88.0
23,87.0,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848,-5.0,86.0
24,88.0,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666,-7.0,88.0
25,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792,11.0,82.0
26,90.0,Maldives,0.747,79.9182,12.63561,7.322,15448.12788,-14.0,97.0
27,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546,13.0,96.0
28,91.0,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456,-8.0,100.0
29,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125,34.0,90.0
30,91.0,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155,-1.0,93.0
31,95.0,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273,11.0,99.0
32,96.0,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532,9.0,90.0
33,97.0,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056,4.0,97.0
34,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477,10.0,94.0
35,99.0,Fiji,0.73,67.114,14.73679,10.921548,9980.110866,9.0,94.0
36,99.0,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033,-6.0,92.0
37,101.0,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725,18.0,107.0
38,102.0,Dominica,0.72,72.814,13.319186,8.142186,11487.62422,0.0,106.0
39,102.0,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974,8.0,104.0
40,104.0,Libya,0.718,71.9112,12.85428,7.599985,15335.712,-27.0,117.0
41,105.0,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286,-10.0,100.0
42,106.0,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416,21.0,109.0
43,106.0,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381,-7.0,104.0
44,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734,-47.0,107.0
45,109.0,South Africa,0.713,62.341,13.64371,11.37316,12948.37325,-17.0,102.0
46,110.0,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567,4.0,110.0
47,111.0,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374,24.0,112.0
48,112.0,Gabon,0.706,65.821,12.97731,9.436,13366.93455,-25.0,113.0
49,112.0,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467,-1.0,103.0
50,114.0,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836,-11.0,116.0
51,115.0,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345,6.0,113.0

In [298]:
#Hacemos una copia del df y analizamos la existencia de valores nulos
level2_better=level2.copy()
level2_better.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52 entries, 0 to 51
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                50 non-null     object
 1   Country                                 51 non-null     object
 2   Human_Development_Index__2021           51 non-null     object
 3   Life_Expectancy_At_Birth2021            51 non-null     object
 4   Expected_Years_Of_Schooling2021         51 non-null     object
 5   Mean_Years_Of_Schooling2021             51 non-null     object
 6   Gross_National_Income__Per_Capita2021   51 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  51 non-null     object
 8   Hdi_Rank2020                            51 non-null     object
dtypes: object(9)
memory usage: 4.1+ KB

In [300]:
#Analizamos los valores nulos en las columnas 1:3
level2_better[level2_better.iloc[:,1:3].isnull().any(axis=1)]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,HIGH HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [301]:
#Eliminamos las filas con valores nulos en las columnas 1:3
level2_better=level2_better[~level2_better.iloc[:,1:3].isnull().any(axis=1)]
level2_better.reset_index(drop=True, inplace=True)
level2_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,67.0,Albania,0.796,76.4626,14.448,11.286455,14131.11039,17.0,68.0
2,68.0,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595,-8.0,64.0
3,68.0,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774,18.0,70.0
4,70.0,Barbados,0.79,77.5714,15.713385,9.852701,12306.341,26.0,71.0
5,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595,2.0,71.0
6,72.0,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775,-17.0,69.0
7,73.0,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055,21.0,75.0
8,74.0,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465,4.0,73.0
9,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212,-16.0,76.0
10,76.0,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117,15.0,77.0
11,77.0,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977,11.0,78.0
12,78.0,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283,-3.0,79.0
13,79.0,China,0.768,78.2107,14.236115,7.600118,17504.39969,-8.0,82.0
14,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037,-11.0,82.0
15,80.0,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189,-1.0,81.0
16,80.0,Palau,0.767,66.0204,15.78432,12.49143,13818.67869,5.0,80.0
17,83.0,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482,37.0,73.0
18,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.89366,13.0,85.0
19,85.0,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939,4.0,87.0
20,86.0,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498,-16.0,88.0
21,87.0,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848,-5.0,86.0
22,88.0,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666,-7.0,88.0
23,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792,11.0,82.0
24,90.0,Maldives,0.747,79.9182,12.63561,7.322,15448.12788,-14.0,97.0
25,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546,13.0,96.0
26,91.0,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456,-8.0,100.0
27,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125,34.0,90.0
28,91.0,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155,-1.0,93.0
29,95.0,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273,11.0,99.0
30,96.0,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532,9.0,90.0
31,97.0,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056,4.0,97.0
32,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477,10.0,94.0
33,99.0,Fiji,0.73,67.114,14.73679,10.921548,9980.110866,9.0,94.0
34,99.0,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033,-6.0,92.0
35,101.0,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725,18.0,107.0
36,102.0,Dominica,0.72,72.814,13.319186,8.142186,11487.62422,0.0,106.0
37,102.0,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974,8.0,104.0
38,104.0,Libya,0.718,71.9112,12.85428,7.599985,15335.712,-27.0,117.0
39,105.0,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286,-10.0,100.0
40,106.0,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416,21.0,109.0
41,106.0,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381,-7.0,104.0
42,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734,-47.0,107.0
43,109.0,South Africa,0.713,62.341,13.64371,11.37316,12948.37325,-17.0,102.0
44,110.0,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567,4.0,110.0
45,111.0,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374,24.0,112.0
46,112.0,Gabon,0.706,65.821,12.97731,9.436,13366.93455,-25.0,113.0
47,112.0,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467,-1.0,103.0
48,114.0,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836,-11.0,116.0
49,115.0,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345,6.0,113.0

In [302]:
#Buscamos valores NO numericos de una fila
level2_better[level2_better.iloc[:, 2].str.contains('\D+').fillna(False)]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1

In [303]:
#Eliminamos la fila de cadenas
level2_better=level2_better[~level2_better.iloc[:, 2].str.contains('\D+').fillna(False)]
level2_better.reset_index(drop=True, inplace=True)
level2_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,67.0,Albania,0.796,76.4626,14.448,11.286455,14131.11039,17.0,68.0
1,68.0,Bulgaria,0.795,71.798,13.89729,11.41318,23078.95595,-8.0,64.0
2,68.0,Grenada,0.795,74.9362,18.66202,9.032104,13483.5774,18.0,70.0
3,70.0,Barbados,0.79,77.5714,15.713385,9.852701,12306.341,26.0,71.0
4,71.0,Antigua and Barbuda,0.788,78.4968,14.184626,9.293741,16792.36595,2.0,71.0
5,72.0,Seychelles,0.785,71.2945,13.94161,10.28312,25830.61775,-17.0,69.0
6,73.0,Sri Lanka,0.782,76.3991,14.139905,10.8273,12578.22055,21.0,75.0
7,74.0,Bosnia and Herzegovina,0.78,75.3003,13.8,10.53632,15241.91465,4.0,73.0
8,75.0,Saint Kitts and Nevis,0.777,71.6822,15.427692,8.662745,23358.33212,-16.0,76.0
9,76.0,Iran (Islamic Republic of),0.774,73.8749,14.61525,10.636453,13000.7117,15.0,77.0
10,77.0,Ukraine,0.773,71.624,14.956569,11.13142,13255.50977,11.0,78.0
11,78.0,North Macedonia,0.77,73.8415,13.624432,10.22815,15917.75283,-3.0,79.0
12,79.0,China,0.768,78.2107,14.236115,7.600118,17504.39969,-8.0,82.0
13,80.0,Dominican Republic,0.767,72.6146,14.466558,9.306864,17989.60037,-11.0,82.0
14,80.0,Moldova (Republic of),0.767,68.8459,14.433,11.82159,14875.33189,-1.0,81.0
15,80.0,Palau,0.767,66.0204,15.78432,12.49143,13818.67869,5.0,80.0
16,83.0,Cuba,0.764,73.6829,14.44306,12.497734,7878.847482,37.0,73.0
17,84.0,Peru,0.762,72.3769,15.387734,9.885519,12245.89366,13.0,85.0
18,85.0,Armenia,0.759,72.0431,13.11676,11.3303,13157.9939,4.0,87.0
19,86.0,Mexico,0.758,70.2127,14.86444,9.22105,17896.29498,-16.0,88.0
20,87.0,Brazil,0.754,72.7504,15.59906,8.128814,14369.88848,-5.0,86.0
21,88.0,Colombia,0.752,72.8296,14.44275,8.86286,14384.35666,-7.0,88.0
22,89.0,Saint Vincent and the Grenadines,0.751,69.6291,14.672206,10.83343,11961.08792,11.0,82.0
23,90.0,Maldives,0.747,79.9182,12.63561,7.322,15448.12788,-14.0,97.0
24,91.0,Algeria,0.745,76.3767,14.626896,8.069284,10800.22546,13.0,96.0
25,91.0,Azerbaijan,0.745,69.3658,13.49689,10.54297,14256.74456,-8.0,100.0
26,91.0,Tonga,0.745,70.9857,16.048571,11.392594,6822.03125,34.0,90.0
27,91.0,Turkmenistan,0.745,69.2644,13.2104,11.26139,13020.7155,-1.0,93.0
28,95.0,Ecuador,0.74,73.67,14.62423,8.81712,10311.63273,11.0,99.0
29,96.0,Mongolia,0.739,70.9754,14.98035,9.4237,10588.22532,9.0,90.0
30,97.0,Egypt,0.731,70.2207,13.7865,9.573026,11731.69056,4.0,97.0
31,97.0,Tunisia,0.731,73.7719,15.425382,7.431599,10257.54477,10.0,94.0
32,99.0,Fiji,0.73,67.114,14.73679,10.921548,9980.110866,9.0,94.0
33,99.0,Suriname,0.73,70.2743,13.035644,9.776801,12672.20033,-6.0,92.0
34,101.0,Uzbekistan,0.727,70.8616,12.47714,11.89559,7916.785725,18.0,107.0
35,102.0,Dominica,0.72,72.814,13.319186,8.142186,11487.62422,0.0,106.0
36,102.0,Jordan,0.72,74.2563,10.64656,10.44668,9923.714974,8.0,104.0
37,104.0,Libya,0.718,71.9112,12.85428,7.599985,15335.712,-27.0,117.0
38,105.0,Paraguay,0.717,70.2617,12.987991,8.86184,12349.286,-10.0,100.0
39,106.0,"Palestine, State of",0.715,73.4727,13.35801,9.93848,6582.899416,21.0,109.0
40,106.0,Saint Lucia,0.715,71.1114,12.86611,8.54504,12048.30381,-7.0,104.0
41,108.0,Guyana,0.714,65.6734,12.502722,8.617477,22464.65734,-47.0,107.0
42,109.0,South Africa,0.713,62.341,13.64371,11.37316,12948.37325,-17.0,102.0
43,110.0,Jamaica,0.709,70.5003,13.40492,9.154629,8834.47567,4.0,110.0
44,111.0,Samoa,0.707,72.7675,12.418859,11.4038,5307.953374,24.0,112.0
45,112.0,Gabon,0.706,65.821,12.97731,9.436,13366.93455,-25.0,113.0
46,112.0,Lebanon,0.706,75.0472,11.28587,8.718636,9525.831467,-1.0,103.0
47,114.0,Indonesia,0.705,67.5703,13.748894,8.55651,11466.06836,-11.0,116.0
48,115.0,Viet Nam,0.703,73.6181,12.951932,8.37028,7867.371345,6.0,113.0

In [304]:
#Probar si existen valores nulos en la columna "Hdi_Rank"
level2_better[level2_better.Hdi_Rank.isnull()]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [305]:
#Ahora validando si existe alguna columna nula
level2_better[level2_better.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [306]:
#Validamos la calidad de nuestros datos
level2_better.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49 entries, 0 to 48
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                49 non-null     object
 1   Country                                 49 non-null     object
 2   Human_Development_Index__2021           49 non-null     object
 3   Life_Expectancy_At_Birth2021            49 non-null     object
 4   Expected_Years_Of_Schooling2021         49 non-null     object
 5   Mean_Years_Of_Schooling2021             49 non-null     object
 6   Gross_National_Income__Per_Capita2021   49 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  49 non-null     object
 8   Hdi_Rank2020                            49 non-null     object
dtypes: object(9)
memory usage: 3.6+ KB

In [307]:
#Evaluamos si los elementos de la columna "Gross_National_Income__Per_Capita2021" son cadenas o textos
level2_better.iloc[:,6]

0     14131.11039
1     23078.95595
2      13483.5774
3       12306.341
4     16792.36595
5     25830.61775
6     12578.22055
7     15241.91465
8     23358.33212
9      13000.7117
10    13255.50977
11    15917.75283
12    17504.39969
13    17989.60037
14    14875.33189
15    13818.67869
16    7878.847482
17    12245.89366
18     13157.9939
19    17896.29498
20    14369.88848
21    14384.35666
22    11961.08792
23    15448.12788
24    10800.22546
25    14256.74456
26     6822.03125
27     13020.7155
28    10311.63273
29    10588.22532
30    11731.69056
31    10257.54477
32    9980.110866
33    12672.20033
34    7916.785725
35    11487.62422
36    9923.714974
37      15335.712
38      12349.286
39    6582.899416
40    12048.30381
41    22464.65734
42    12948.37325
43     8834.47567
44    5307.953374
45    13366.93455
46    9525.831467
47    11466.06836
48    7867.371345
Name: Gross_National_Income__Per_Capita2021, dtype: object

In [308]:
#Vamos a transformar todas las columnas en numericos sin afectar a la columna "Country"
level2_clean=level2_better.set_index('Country')
level2_formatted=level2_clean.apply(pd.to_numeric)
level2_formatted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 49 entries, Albania to Viet Nam
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                49 non-null     float64
 1   Human_Development_Index__2021           49 non-null     float64
 2   Life_Expectancy_At_Birth2021            49 non-null     float64
 3   Expected_Years_Of_Schooling2021         49 non-null     float64
 4   Mean_Years_Of_Schooling2021             49 non-null     float64
 5   Gross_National_Income__Per_Capita2021   49 non-null     float64
 6   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  49 non-null     float64
 7   Hdi_Rank2020                            49 non-null     float64
dtypes: float64(8)
memory usage: 3.4+ KB

In [309]:
#Devolvemos del indice a la columna "Country"
level2_formatted.reset_index(drop=False,inplace=True)
level2_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,Albania,67.0,0.796,76.4626,14.448000,11.286455,14131.110390,17.0,68.0
1,Bulgaria,68.0,0.795,71.7980,13.897290,11.413180,23078.955950,-8.0,64.0
2,Grenada,68.0,0.795,74.9362,18.662020,9.032104,13483.577400,18.0,70.0
3,Barbados,70.0,0.790,77.5714,15.713385,9.852701,12306.341000,26.0,71.0
4,Antigua and Barbuda,71.0,0.788,78.4968,14.184626,9.293741,16792.365950,2.0,71.0
5,Seychelles,72.0,0.785,71.2945,13.941610,10.283120,25830.617750,-17.0,69.0
6,Sri Lanka,73.0,0.782,76.3991,14.139905,10.827300,12578.220550,21.0,75.0
7,Bosnia and Herzegovina,74.0,0.780,75.3003,13.800000,10.536320,15241.914650,4.0,73.0
8,Saint Kitts and Nevis,75.0,0.777,71.6822,15.427692,8.662745,23358.332120,-16.0,76.0
9,Iran (Islamic Republic of),76.0,0.774,73.8749,14.615250,10.636453,13000.711700,15.0,77.0
10,Ukraine,77.0,0.773,71.6240,14.956569,11.131420,13255.509770,11.0,78.0
11,North Macedonia,78.0,0.770,73.8415,13.624432,10.228150,15917.752830,-3.0,79.0
12,China,79.0,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82.0
13,Dominican Republic,80.0,0.767,72.6146,14.466558,9.306864,17989.600370,-11.0,82.0
14,Moldova (Republic of),80.0,0.767,68.8459,14.433000,11.821590,14875.331890,-1.0,81.0
15,Palau,80.0,0.767,66.0204,15.784320,12.491430,13818.678690,5.0,80.0
16,Cuba,83.0,0.764,73.6829,14.443060,12.497734,7878.847482,37.0,73.0
17,Peru,84.0,0.762,72.3769,15.387734,9.885519,12245.893660,13.0,85.0
18,Armenia,85.0,0.759,72.0431,13.116760,11.330300,13157.993900,4.0,87.0
19,Mexico,86.0,0.758,70.2127,14.864440,9.221050,17896.294980,-16.0,88.0
20,Brazil,87.0,0.754,72.7504,15.599060,8.128814,14369.888480,-5.0,86.0
21,Colombia,88.0,0.752,72.8296,14.442750,8.862860,14384.356660,-7.0,88.0
22,Saint Vincent and the Grenadines,89.0,0.751,69.6291,14.672206,10.833430,11961.087920,11.0,82.0
23,Maldives,90.0,0.747,79.9182,12.635610,7.322000,15448.127880,-14.0,97.0
24,Algeria,91.0,0.745,76.3767,14.626896,8.069284,10800.225460,13.0,96.0
25,Azerbaijan,91.0,0.745,69.3658,13.496890,10.542970,14256.744560,-8.0,100.0
26,Tonga,91.0,0.745,70.9857,16.048571,11.392594,6822.031250,34.0,90.0
27,Turkmenistan,91.0,0.745,69.2644,13.210400,11.261390,13020.715500,-1.0,93.0
28,Ecuador,95.0,0.740,73.6700,14.624230,8.817120,10311.632730,11.0,99.0
29,Mongolia,96.0,0.739,70.9754,14.980350,9.423700,10588.225320,9.0,90.0
30,Egypt,97.0,0.731,70.2207,13.786500,9.573026,11731.690560,4.0,97.0
31,Tunisia,97.0,0.731,73.7719,15.425382,7.431599,10257.544770,10.0,94.0
32,Fiji,99.0,0.730,67.1140,14.736790,10.921548,9980.110866,9.0,94.0
33,Suriname,99.0,0.730,70.2743,13.035644,9.776801,12672.200330,-6.0,92.0
34,Uzbekistan,101.0,0.727,70.8616,12.477140,11.895590,7916.785725,18.0,107.0
35,Dominica,102.0,0.720,72.8140,13.319186,8.142186,11487.624220,0.0,106.0
36,Jordan,102.0,0.720,74.2563,10.646560,10.446680,9923.714974,8.0,104.0
37,Libya,104.0,0.718,71.9112,12.854280,7.599985,15335.712000,-27.0,117.0
38,Paraguay,105.0,0.717,70.2617,12.987991,8.861840,12349.286000,-10.0,100.0
39,"Palestine, State of",106.0,0.715,73.4727,13.358010,9.938480,6582.899416,21.0,109.0
40,Saint Lucia,106.0,0.715,71.1114,12.866110,8.545040,12048.303810,-7.0,104.0
41,Guyana,108.0,0.714,65.6734,12.502722,8.617477,22464.657340,-47.0,107.0
42,South Africa,109.0,0.713,62.3410,13.643710,11.373160,12948.373250,-17.0,102.0
43,Jamaica,110.0,0.709,70.5003,13.404920,9.154629,8834.475670,4.0,110.0
44,Samoa,111.0,0.707,72.7675,12.418859,11.403800,5307.953374,24.0,112.0
45,Gabon,112.0,0.706,65.8210,12.977310,9.436000,13366.934550,-25.0,113.0
46,Lebanon,112.0,0.706,75.0472,11.285870,8.718636,9525.831467,-1.0,103.0
47,Indonesia,114.0,0.705,67.5703,13.748894,8.556510,11466.068360,-11.0,116.0
48,Viet Nam,115.0,0.703,73.6181,12.951932,8.370280,7867.371345,6.0,113.0

In [310]:
#Colocamos en mayuscula los elementos de la columna "Country"
level2_formatted['Country']=level2_formatted.Country.str.strip()
level2_formatted['Country']=level2_formatted.Country.str.upper()
level2_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,ALBANIA,67.0,0.796,76.4626,14.448000,11.286455,14131.110390,17.0,68.0
1,BULGARIA,68.0,0.795,71.7980,13.897290,11.413180,23078.955950,-8.0,64.0
2,GRENADA,68.0,0.795,74.9362,18.662020,9.032104,13483.577400,18.0,70.0
3,BARBADOS,70.0,0.790,77.5714,15.713385,9.852701,12306.341000,26.0,71.0
4,ANTIGUA AND BARBUDA,71.0,0.788,78.4968,14.184626,9.293741,16792.365950,2.0,71.0
5,SEYCHELLES,72.0,0.785,71.2945,13.941610,10.283120,25830.617750,-17.0,69.0
6,SRI LANKA,73.0,0.782,76.3991,14.139905,10.827300,12578.220550,21.0,75.0
7,BOSNIA AND HERZEGOVINA,74.0,0.780,75.3003,13.800000,10.536320,15241.914650,4.0,73.0
8,SAINT KITTS AND NEVIS,75.0,0.777,71.6822,15.427692,8.662745,23358.332120,-16.0,76.0
9,IRAN (ISLAMIC REPUBLIC OF),76.0,0.774,73.8749,14.615250,10.636453,13000.711700,15.0,77.0
10,UKRAINE,77.0,0.773,71.6240,14.956569,11.131420,13255.509770,11.0,78.0
11,NORTH MACEDONIA,78.0,0.770,73.8415,13.624432,10.228150,15917.752830,-3.0,79.0
12,CHINA,79.0,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82.0
13,DOMINICAN REPUBLIC,80.0,0.767,72.6146,14.466558,9.306864,17989.600370,-11.0,82.0
14,MOLDOVA (REPUBLIC OF),80.0,0.767,68.8459,14.433000,11.821590,14875.331890,-1.0,81.0
15,PALAU,80.0,0.767,66.0204,15.784320,12.491430,13818.678690,5.0,80.0
16,CUBA,83.0,0.764,73.6829,14.443060,12.497734,7878.847482,37.0,73.0
17,PERU,84.0,0.762,72.3769,15.387734,9.885519,12245.893660,13.0,85.0
18,ARMENIA,85.0,0.759,72.0431,13.116760,11.330300,13157.993900,4.0,87.0
19,MEXICO,86.0,0.758,70.2127,14.864440,9.221050,17896.294980,-16.0,88.0
20,BRAZIL,87.0,0.754,72.7504,15.599060,8.128814,14369.888480,-5.0,86.0
21,COLOMBIA,88.0,0.752,72.8296,14.442750,8.862860,14384.356660,-7.0,88.0
22,SAINT VINCENT AND THE GRENADINES,89.0,0.751,69.6291,14.672206,10.833430,11961.087920,11.0,82.0
23,MALDIVES,90.0,0.747,79.9182,12.635610,7.322000,15448.127880,-14.0,97.0
24,ALGERIA,91.0,0.745,76.3767,14.626896,8.069284,10800.225460,13.0,96.0
25,AZERBAIJAN,91.0,0.745,69.3658,13.496890,10.542970,14256.744560,-8.0,100.0
26,TONGA,91.0,0.745,70.9857,16.048571,11.392594,6822.031250,34.0,90.0
27,TURKMENISTAN,91.0,0.745,69.2644,13.210400,11.261390,13020.715500,-1.0,93.0
28,ECUADOR,95.0,0.740,73.6700,14.624230,8.817120,10311.632730,11.0,99.0
29,MONGOLIA,96.0,0.739,70.9754,14.980350,9.423700,10588.225320,9.0,90.0
30,EGYPT,97.0,0.731,70.2207,13.786500,9.573026,11731.690560,4.0,97.0
31,TUNISIA,97.0,0.731,73.7719,15.425382,7.431599,10257.544770,10.0,94.0
32,FIJI,99.0,0.730,67.1140,14.736790,10.921548,9980.110866,9.0,94.0
33,SURINAME,99.0,0.730,70.2743,13.035644,9.776801,12672.200330,-6.0,92.0
34,UZBEKISTAN,101.0,0.727,70.8616,12.477140,11.895590,7916.785725,18.0,107.0
35,DOMINICA,102.0,0.720,72.8140,13.319186,8.142186,11487.624220,0.0,106.0
36,JORDAN,102.0,0.720,74.2563,10.646560,10.446680,9923.714974,8.0,104.0
37,LIBYA,104.0,0.718,71.9112,12.854280,7.599985,15335.712000,-27.0,117.0
38,PARAGUAY,105.0,0.717,70.2617,12.987991,8.861840,12349.286000,-10.0,100.0
39,"PALESTINE, STATE OF",106.0,0.715,73.4727,13.358010,9.938480,6582.899416,21.0,109.0
40,SAINT LUCIA,106.0,0.715,71.1114,12.866110,8.545040,12048.303810,-7.0,104.0
41,GUYANA,108.0,0.714,65.6734,12.502722,8.617477,22464.657340,-47.0,107.0
42,SOUTH AFRICA,109.0,0.713,62.3410,13.643710,11.373160,12948.373250,-17.0,102.0
43,JAMAICA,110.0,0.709,70.5003,13.404920,9.154629,8834.475670,4.0,110.0
44,SAMOA,111.0,0.707,72.7675,12.418859,11.403800,5307.953374,24.0,112.0
45,GABON,112.0,0.706,65.8210,12.977310,9.436000,13366.934550,-25.0,113.0
46,LEBANON,112.0,0.706,75.0472,11.285870,8.718636,9525.831467,-1.0,103.0
47,INDONESIA,114.0,0.705,67.5703,13.748894,8.556510,11466.068360,-11.0,116.0
48,VIET NAM,115.0,0.703,73.6181,12.951932,8.370280,7867.371345,6.0,113.0

In [311]:
#Agregamos la columna de indicador de desarrollo
level2_formatted['Development'] = "HIGH HUMAN DEVELOPMENT"
level2_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,ALBANIA,67.0,0.796,76.4626,14.448000,11.286455,14131.110390,17.0,68.0,HIGH HUMAN DEVELOPMENT
1,BULGARIA,68.0,0.795,71.7980,13.897290,11.413180,23078.955950,-8.0,64.0,HIGH HUMAN DEVELOPMENT
2,GRENADA,68.0,0.795,74.9362,18.662020,9.032104,13483.577400,18.0,70.0,HIGH HUMAN DEVELOPMENT
3,BARBADOS,70.0,0.790,77.5714,15.713385,9.852701,12306.341000,26.0,71.0,HIGH HUMAN DEVELOPMENT
4,ANTIGUA AND BARBUDA,71.0,0.788,78.4968,14.184626,9.293741,16792.365950,2.0,71.0,HIGH HUMAN DEVELOPMENT
5,SEYCHELLES,72.0,0.785,71.2945,13.941610,10.283120,25830.617750,-17.0,69.0,HIGH HUMAN DEVELOPMENT
6,SRI LANKA,73.0,0.782,76.3991,14.139905,10.827300,12578.220550,21.0,75.0,HIGH HUMAN DEVELOPMENT
7,BOSNIA AND HERZEGOVINA,74.0,0.780,75.3003,13.800000,10.536320,15241.914650,4.0,73.0,HIGH HUMAN DEVELOPMENT
8,SAINT KITTS AND NEVIS,75.0,0.777,71.6822,15.427692,8.662745,23358.332120,-16.0,76.0,HIGH HUMAN DEVELOPMENT
9,IRAN (ISLAMIC REPUBLIC OF),76.0,0.774,73.8749,14.615250,10.636453,13000.711700,15.0,77.0,HIGH HUMAN DEVELOPMENT
10,UKRAINE,77.0,0.773,71.6240,14.956569,11.131420,13255.509770,11.0,78.0,HIGH HUMAN DEVELOPMENT
11,NORTH MACEDONIA,78.0,0.770,73.8415,13.624432,10.228150,15917.752830,-3.0,79.0,HIGH HUMAN DEVELOPMENT
12,CHINA,79.0,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82.0,HIGH HUMAN DEVELOPMENT
13,DOMINICAN REPUBLIC,80.0,0.767,72.6146,14.466558,9.306864,17989.600370,-11.0,82.0,HIGH HUMAN DEVELOPMENT
14,MOLDOVA (REPUBLIC OF),80.0,0.767,68.8459,14.433000,11.821590,14875.331890,-1.0,81.0,HIGH HUMAN DEVELOPMENT
15,PALAU,80.0,0.767,66.0204,15.784320,12.491430,13818.678690,5.0,80.0,HIGH HUMAN DEVELOPMENT
16,CUBA,83.0,0.764,73.6829,14.443060,12.497734,7878.847482,37.0,73.0,HIGH HUMAN DEVELOPMENT
17,PERU,84.0,0.762,72.3769,15.387734,9.885519,12245.893660,13.0,85.0,HIGH HUMAN DEVELOPMENT
18,ARMENIA,85.0,0.759,72.0431,13.116760,11.330300,13157.993900,4.0,87.0,HIGH HUMAN DEVELOPMENT
19,MEXICO,86.0,0.758,70.2127,14.864440,9.221050,17896.294980,-16.0,88.0,HIGH HUMAN DEVELOPMENT
20,BRAZIL,87.0,0.754,72.7504,15.599060,8.128814,14369.888480,-5.0,86.0,HIGH HUMAN DEVELOPMENT
21,COLOMBIA,88.0,0.752,72.8296,14.442750,8.862860,14384.356660,-7.0,88.0,HIGH HUMAN DEVELOPMENT
22,SAINT VINCENT AND THE GRENADINES,89.0,0.751,69.6291,14.672206,10.833430,11961.087920,11.0,82.0,HIGH HUMAN DEVELOPMENT
23,MALDIVES,90.0,0.747,79.9182,12.635610,7.322000,15448.127880,-14.0,97.0,HIGH HUMAN DEVELOPMENT
24,ALGERIA,91.0,0.745,76.3767,14.626896,8.069284,10800.225460,13.0,96.0,HIGH HUMAN DEVELOPMENT
25,AZERBAIJAN,91.0,0.745,69.3658,13.496890,10.542970,14256.744560,-8.0,100.0,HIGH HUMAN DEVELOPMENT
26,TONGA,91.0,0.745,70.9857,16.048571,11.392594,6822.031250,34.0,90.0,HIGH HUMAN DEVELOPMENT
27,TURKMENISTAN,91.0,0.745,69.2644,13.210400,11.261390,13020.715500,-1.0,93.0,HIGH HUMAN DEVELOPMENT
28,ECUADOR,95.0,0.740,73.6700,14.624230,8.817120,10311.632730,11.0,99.0,HIGH HUMAN DEVELOPMENT
29,MONGOLIA,96.0,0.739,70.9754,14.980350,9.423700,10588.225320,9.0,90.0,HIGH HUMAN DEVELOPMENT
30,EGYPT,97.0,0.731,70.2207,13.786500,9.573026,11731.690560,4.0,97.0,HIGH HUMAN DEVELOPMENT
31,TUNISIA,97.0,0.731,73.7719,15.425382,7.431599,10257.544770,10.0,94.0,HIGH HUMAN DEVELOPMENT
32,FIJI,99.0,0.730,67.1140,14.736790,10.921548,9980.110866,9.0,94.0,HIGH HUMAN DEVELOPMENT
33,SURINAME,99.0,0.730,70.2743,13.035644,9.776801,12672.200330,-6.0,92.0,HIGH HUMAN DEVELOPMENT
34,UZBEKISTAN,101.0,0.727,70.8616,12.477140,11.895590,7916.785725,18.0,107.0,HIGH HUMAN DEVELOPMENT
35,DOMINICA,102.0,0.720,72.8140,13.319186,8.142186,11487.624220,0.0,106.0,HIGH HUMAN DEVELOPMENT
36,JORDAN,102.0,0.720,74.2563,10.646560,10.446680,9923.714974,8.0,104.0,HIGH HUMAN DEVELOPMENT
37,LIBYA,104.0,0.718,71.9112,12.854280,7.599985,15335.712000,-27.0,117.0,HIGH HUMAN DEVELOPMENT
38,PARAGUAY,105.0,0.717,70.2617,12.987991,8.861840,12349.286000,-10.0,100.0,HIGH HUMAN DEVELOPMENT
39,"PALESTINE, STATE OF",106.0,0.715,73.4727,13.358010,9.938480,6582.899416,21.0,109.0,HIGH HUMAN DEVELOPMENT
40,SAINT LUCIA,106.0,0.715,71.1114,12.866110,8.545040,12048.303810,-7.0,104.0,HIGH HUMAN DEVELOPMENT
41,GUYANA,108.0,0.714,65.6734,12.502722,8.617477,22464.657340,-47.0,107.0,HIGH HUMAN DEVELOPMENT
42,SOUTH AFRICA,109.0,0.713,62.3410,13.643710,11.373160,12948.373250,-17.0,102.0,HIGH HUMAN DEVELOPMENT
43,JAMAICA,110.0,0.709,70.5003,13.404920,9.154629,8834.475670,4.0,110.0,HIGH HUMAN DEVELOPMENT
44,SAMOA,111.0,0.707,72.7675,12.418859,11.403800,5307.953374,24.0,112.0,HIGH HUMAN DEVELOPMENT
45,GABON,112.0,0.706,65.8210,12.977310,9.436000,13366.934550,-25.0,113.0,HIGH HUMAN DEVELOPMENT
46,LEBANON,112.0,0.706,75.0472,11.285870,8.718636,9525.831467,-1.0,103.0,HIGH HUMAN DEVELOPMENT
47,INDONESIA,114.0,0.705,67.5703,13.748894,8.556510,11466.068360,-11.0,116.0,HIGH HUMAN DEVELOPMENT
48,VIET NAM,115.0,0.703,73.6181,12.951932,8.370280,7867.371345,6.0,113.0,HIGH HUMAN DEVELOPMENT

In [312]:
#Leemos el tercer archivo de excel Level3
level3=pd.read_excel(append_data_path+"/level3.xlsx")

In [313]:
level3

,HDI rank,Country,Human Development Index (HDI),Unnamed: 3,Life expectancy at birth,Unnamed: 5,Expected years of schooling,Unnamed: 7,Mean years of schooling,Unnamed: 9,Gross national income (GNI) per capita,Unnamed: 11,GNI per capita rank minus HDI rank,Unnamed: 13,HDI rank.1
0,NaN,NaN,2021.000,NaN,2021.0000,NaN,2021.000000,a,2021.000000,a,2021.000000,NaN,2021.0,b,2020.0
1,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,116.0,Philippines,0.699,NaN,69.2664,NaN,13.126570,NaN,8.969100,NaN,8920.428468,NaN,-3.0,NaN,113.0
3,117.0,Botswana,0.693,NaN,61.1409,NaN,12.265138,e,10.340000,NaN,16198.318410,NaN,-43.0,NaN,110.0
4,118.0,Bolivia (Plurinational State of),0.692,NaN,63.6304,NaN,14.946971,NaN,9.827750,NaN,8111.190194,NaN,0.0,NaN,119.0
5,118.0,Kyrgyzstan,0.692,NaN,69.9774,NaN,13.195300,NaN,11.374106,n,4566.303831,NaN,26.0,NaN,121.0
6,120.0,Venezuela (Bolivarian Republic of),0.691,NaN,70.5536,NaN,12.816080,p,11.107277,e,4810.882621,t,20.0,NaN,118.0
7,121.0,Iraq,0.686,NaN,70.3779,NaN,12.087473,s,7.905593,m,9977.249073,NaN,-12.0,NaN,122.0
8,122.0,Tajikistan,0.685,NaN,71.5942,NaN,11.653036,e,11.333394,n,4547.742427,NaN,23.0,NaN,126.0
9,123.0,Belize,0.683,NaN,70.4697,NaN,12.991690,NaN,8.847600,NaN,6309.099778,NaN,6.0,NaN,120.0
10,123.0,Morocco,0.683,NaN,74.0419,NaN,14.151910,NaN,5.916000,NaN,7302.819170,NaN,1.0,NaN,122.0
11,125.0,El Salvador,0.675,NaN,70.7479,NaN,12.671348,o,7.150930,NaN,8295.665889,NaN,-8.0,NaN,124.0
12,126.0,Nicaragua,0.667,NaN,73.8368,NaN,12.641358,o,7.144000,NaN,5624.793595,NaN,6.0,NaN,129.0
13,127.0,Bhutan,0.666,NaN,71.8150,NaN,13.225005,e,5.170262,e,9437.541512,NaN,-15.0,NaN,125.0
14,128.0,Cabo Verde,0.662,NaN,74.0518,NaN,12.554614,e,6.287719,p,6230.200199,NaN,2.0,NaN,127.0
15,129.0,Bangladesh,0.661,NaN,72.3811,NaN,12.441980,NaN,7.379060,NaN,5472.104781,NaN,4.0,NaN,128.0
16,130.0,Tuvalu,0.641,NaN,64.5466,NaN,9.404430,e,10.573108,NaN,6351.435899,NaN,-2.0,NaN,131.0
17,131.0,Marshall Islands,0.639,NaN,65.2688,NaN,10.239320,NaN,10.883140,NaN,4619.535393,NaN,12.0,NaN,131.0
18,132.0,India,0.633,NaN,67.2398,NaN,11.874620,NaN,6.655109,n,6589.980037,NaN,-6.0,NaN,130.0
19,133.0,Ghana,0.632,NaN,63.7954,NaN,12.047780,NaN,8.329887,n,5744.504017,NaN,-2.0,NaN,135.0
20,134.0,Micronesia (Federated States of),0.628,NaN,70.7100,NaN,11.549480,j,7.804956,l,3696.173945,NaN,22.0,NaN,136.0
21,135.0,Guatemala,0.627,NaN,69.2368,NaN,10.562450,NaN,5.681300,NaN,8723.285317,NaN,-20.0,NaN,133.0
22,136.0,Kiribati,0.624,NaN,67.4172,NaN,11.801993,NaN,7.984462,s,4062.586034,NaN,14.0,NaN,137.0
23,137.0,Honduras,0.621,NaN,70.1229,NaN,10.132814,o,7.088480,NaN,5297.955301,NaN,-1.0,NaN,138.0
24,138.0,Sao Tome and Principe,0.618,NaN,67.5912,NaN,13.365385,NaN,6.215599,m,4021.350815,NaN,13.0,NaN,139.0
25,139.0,Namibia,0.615,NaN,59.2690,NaN,11.927207,u,7.192013,n,8633.504452,NaN,-23.0,NaN,134.0
26,140.0,Lao People's Democratic Republic,0.607,NaN,68.0608,NaN,10.136110,NaN,5.374000,NaN,7699.579617,NaN,-18.0,NaN,142.0
27,140.0,Timor-Leste,0.607,NaN,67.7369,NaN,12.616098,p,5.436790,NaN,4460.869435,NaN,7.0,NaN,140.0
28,140.0,Vanuatu,0.607,NaN,70.4490,NaN,11.535315,e,7.064846,v,3085.411633,NaN,23.0,NaN,142.0
29,143.0,Nepal,0.602,NaN,68.4495,NaN,12.886950,NaN,5.121793,n,3877.315444,NaN,10.0,NaN,144.0
30,144.0,Eswatini (Kingdom of),0.597,NaN,57.0657,NaN,13.744346,e,5.596000,NaN,7678.591873,NaN,-21.0,NaN,141.0
31,145.0,Equatorial Guinea,0.596,NaN,60.5943,NaN,9.734940,l,5.910863,j,12073.959930,NaN,-47.0,NaN,147.0
32,146.0,Cambodia,0.593,NaN,69.5835,NaN,11.467720,w,5.088000,NaN,4078.697154,NaN,3.0,NaN,148.0
33,146.0,Zimbabwe,0.593,NaN,59.2531,NaN,12.110969,e,8.710909,e,3809.887158,NaN,9.0,NaN,145.0
34,148.0,Angola,0.586,NaN,61.6434,NaN,12.172100,NaN,5.417391,NaN,5465.617791,NaN,-14.0,NaN,149.0
35,149.0,Myanmar,0.585,NaN,65.6716,NaN,10.909138,e,6.376800,NaN,3850.524234,NaN,5.0,NaN,145.0
36,150.0,Syrian Arab Republic,0.577,NaN,72.0627,NaN,9.164220,NaN,5.100000,l,4191.933893,x,-2.0,NaN,152.0
37,151.0,Cameroon,0.576,NaN,60.3334,NaN,13.108599,e,6.151310,n,3620.932408,NaN,6.0,NaN,150.0
38,152.0,Kenya,0.575,NaN,61.4270,NaN,10.698558,u,6.652000,NaN,4473.570344,NaN,-6.0,NaN,150.0
39,153.0,Congo,0.571,NaN,63.5187,NaN,12.330815,e,6.166000,NaN,2889.283521,NaN,11.0,NaN,153.0
40,154.0,Zambia,0.565,NaN,61.2234,NaN,10.928760,w,7.187091,n,3217.767739,NaN,7.0,NaN,154.0
41,155.0,Solomon Islands,0.564,NaN,70.3477,NaN,10.328690,e,5.711848,s,2481.511362,NaN,13.0,NaN,155.0
42,156.0,Comoros,0.558,NaN,63.4174,NaN,11.924324,e,5.078649,l,3142.064119,NaN,6.0,NaN,156.0
43,156.0,Papua New Guinea,0.558,NaN,65.3506,NaN,10.360771,u,4.740000,NaN,4008.623573,NaN,-4.0,NaN,157.0
44,158.0,Mauritania,0.556,NaN,64.3636,NaN,9.376160,NaN,4.918805,n,5075.305711,NaN,-20.0,NaN,158.0
45,159.0,CÃ´te d'Ivoire,0.550,NaN,58.5983,NaN,10.675580,NaN,5.199139,n,5217.448516,NaN,-22.0,NaN,159.0

In [314]:
#Analizamos la tabla y notamos que las cabeceras "Unnamed" no aportan informacion
level3 = level3.loc[:, ~level3.columns.str.startswith('Unnamed')]

In [315]:
#Verificamos si hay columnas con valores nulos
level3[level3.isnull().all(axis=1)]

Empty DataFrame
Columns: [HDI rank, Country, Human Development Index (HDI) , Life expectancy at birth, Expected years of schooling, Mean years of schooling, Gross national income (GNI) per capita, GNI per capita rank minus HDI rank, HDI rank.1]
Index: []

In [316]:
#Convertir las cabeceras en la primera fila
level3.loc[-1] = level3.columns  # AÃ±adir las cabeceras como la primera fila
level3.index = level3.index + 1  # Desplazar los Ã­ndices hacia abajo
level3 = level3.sort_index()  # Ordenar por Ã­ndice

#Eliminar las cabeceras
level3.columns = range(level3.shape[1])
level3

C:\Users\ASUS\AppData\Local\Temp\ipykernel_4620\712585666.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  level3.loc[-1] = level3.columns  # AÃ±adir las cabeceras como la primera fila

,0,1,2,3,4,5,6,7,8
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,116.0,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468,-3.0,113.0
4,117.0,Botswana,0.693,61.1409,12.265138,10.34,16198.31841,-43.0,110.0
5,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194,0.0,119.0
6,118.0,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831,26.0,121.0
7,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621,20.0,118.0
8,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
9,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
10,123.0,Belize,0.683,70.4697,12.99169,8.8476,6309.099778,6.0,120.0
11,123.0,Morocco,0.683,74.0419,14.15191,5.916,7302.81917,1.0,122.0
12,125.0,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889,-8.0,124.0
13,126.0,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595,6.0,129.0
14,127.0,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512,-15.0,125.0
15,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
16,129.0,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781,4.0,128.0
17,130.0,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899,-2.0,131.0
18,131.0,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393,12.0,131.0
19,132.0,India,0.633,67.2398,11.87462,6.655109,6589.980037,-6.0,130.0
20,133.0,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017,-2.0,135.0
21,134.0,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945,22.0,136.0
22,135.0,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317,-20.0,133.0
23,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
24,137.0,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301,-1.0,138.0
25,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
26,139.0,Namibia,0.615,59.269,11.927207,7.192013,8633.504452,-23.0,134.0
27,140.0,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617,-18.0,142.0
28,140.0,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435,7.0,140.0
29,140.0,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633,23.0,142.0
30,143.0,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444,10.0,144.0
31,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873,-21.0,141.0
32,145.0,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993,-47.0,147.0
33,146.0,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154,3.0,148.0
34,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
35,148.0,Angola,0.586,61.6434,12.1721,5.417391,5465.617791,-14.0,149.0
36,149.0,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234,5.0,145.0
37,150.0,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893,-2.0,152.0
38,151.0,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408,6.0,150.0
39,152.0,Kenya,0.575,61.427,10.698558,6.652,4473.570344,-6.0,150.0
40,153.0,Congo,0.571,63.5187,12.330815,6.166,2889.283521,11.0,153.0
41,154.0,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739,7.0,154.0
42,155.0,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362,13.0,155.0
43,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
44,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573,-4.0,157.0
45,158.0,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711,-20.0,158.0
46,159.0,CÃ´te d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516,-22.0,159.0

In [317]:
#Analizando las cabeceras de las columnas notamos un patron y buscamos la forma de limpiar dichas cabeceras
[a for a in zip(level3.iloc[0,:],level3.iloc[1,:])]

[('HDI rank', nan),
 ('Country', nan),
 ('Human Development Index (HDI) ', 2021.0),
 ('Life expectancy at birth', 2021.0),
 ('Expected years of schooling', 2021.0),
 ('Mean years of schooling', 2021.0),
 ('Gross national income (GNI) per capita', 2021.0),
 ('GNI per capita rank minus HDI rank', 2021.0),
 ('HDI rank.1', 2020.0)]

In [318]:
#Juntamos los elementos de la serie en una cadena eliminando la coma que lo separaba
[''.join(map(lambda x: str(int(x)) if pd.notnull(x) and isinstance(x, float) and x.is_integer() else str(x), pd.Series(a).dropna())) for a in zip(level3.iloc[0,:], level3.iloc[1,:])]

['HDI rank',
 'Country',
 'Human Development Index (HDI) 2021',
 'Life expectancy at birth2021',
 'Expected years of schooling2021',
 'Mean years of schooling2021',
 'Gross national income (GNI) per capita2021',
 'GNI per capita rank minus HDI rank2021',
 'HDI rank.12020']

In [319]:
#Modifico las columnas con la serie de textos hallados anteriormente
level3.columns = [''.join(map(lambda x: str(int(x)) if pd.notnull(x) and isinstance(x, float) and x.is_integer() else str(x), pd.Series(a).dropna())) for a in zip(level3.iloc[0,:], level3.iloc[1,:])]
#Renombro la columna por comodidades
level3 = level3.rename(columns={'HDI rank.12020': 'HDI rank2020'})

In [320]:
#Visualizo mis nuevas columnas
level3.columns

Index(['HDI rank', 'Country', 'Human Development Index (HDI) 2021',
       'Life expectancy at birth2021', 'Expected years of schooling2021',
       'Mean years of schooling2021',
       'Gross national income (GNI) per capita2021',
       'GNI per capita rank minus HDI rank2021', 'HDI rank2020'],
      dtype='object')

In [321]:
#Visualizamos el reemplazo los parentesis y espacios por "_"
level3.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)

Index(['Hdi_Rank', 'Country', 'Human_Development_Index__2021',
       'Life_Expectancy_At_Birth2021', 'Expected_Years_Of_Schooling2021',
       'Mean_Years_Of_Schooling2021', 'Gross_National_Income__Per_Capita2021',
       'Gni_Per_Capita_Rank_Minus_Hdi_Rank2021', 'Hdi_Rank2020'],
      dtype='object')

In [322]:
#Reemplazamos los parentesis y espacios por "_"
level3.columns=level3.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)
level3

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,116.0,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468,-3.0,113.0
4,117.0,Botswana,0.693,61.1409,12.265138,10.34,16198.31841,-43.0,110.0
5,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194,0.0,119.0
6,118.0,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831,26.0,121.0
7,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621,20.0,118.0
8,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
9,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
10,123.0,Belize,0.683,70.4697,12.99169,8.8476,6309.099778,6.0,120.0
11,123.0,Morocco,0.683,74.0419,14.15191,5.916,7302.81917,1.0,122.0
12,125.0,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889,-8.0,124.0
13,126.0,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595,6.0,129.0
14,127.0,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512,-15.0,125.0
15,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
16,129.0,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781,4.0,128.0
17,130.0,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899,-2.0,131.0
18,131.0,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393,12.0,131.0
19,132.0,India,0.633,67.2398,11.87462,6.655109,6589.980037,-6.0,130.0
20,133.0,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017,-2.0,135.0
21,134.0,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945,22.0,136.0
22,135.0,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317,-20.0,133.0
23,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
24,137.0,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301,-1.0,138.0
25,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
26,139.0,Namibia,0.615,59.269,11.927207,7.192013,8633.504452,-23.0,134.0
27,140.0,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617,-18.0,142.0
28,140.0,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435,7.0,140.0
29,140.0,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633,23.0,142.0
30,143.0,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444,10.0,144.0
31,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873,-21.0,141.0
32,145.0,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993,-47.0,147.0
33,146.0,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154,3.0,148.0
34,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
35,148.0,Angola,0.586,61.6434,12.1721,5.417391,5465.617791,-14.0,149.0
36,149.0,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234,5.0,145.0
37,150.0,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893,-2.0,152.0
38,151.0,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408,6.0,150.0
39,152.0,Kenya,0.575,61.427,10.698558,6.652,4473.570344,-6.0,150.0
40,153.0,Congo,0.571,63.5187,12.330815,6.166,2889.283521,11.0,153.0
41,154.0,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739,7.0,154.0
42,155.0,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362,13.0,155.0
43,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
44,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573,-4.0,157.0
45,158.0,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711,-20.0,158.0
46,159.0,CÃ´te d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516,-22.0,159.0

In [323]:
#Hacemos una copia del df y analizamos la existencia de valores nulos
level3_better=level3.copy()
level3_better.info()

<class 'pandas.core.frame.DataFrame'>
Index: 47 entries, 0 to 46
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                45 non-null     object
 1   Country                                 46 non-null     object
 2   Human_Development_Index__2021           46 non-null     object
 3   Life_Expectancy_At_Birth2021            46 non-null     object
 4   Expected_Years_Of_Schooling2021         46 non-null     object
 5   Mean_Years_Of_Schooling2021             46 non-null     object
 6   Gross_National_Income__Per_Capita2021   46 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  46 non-null     object
 8   Hdi_Rank2020                            46 non-null     object
dtypes: object(9)
memory usage: 3.7+ KB

In [324]:
#Analizamos los valores nulos en las columnas 1:3
level3_better[level3_better.iloc[:,1:3].isnull().any(axis=1)]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
1,NaN,NaN,2021.0,2021.0,2021.0,2021.0,2021.0,2021.0,2020.0
2,NaN,MEDIUM HUMAN DEVELOPMENT,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [325]:
#Eliminamos las filas con valores nulos en las columnas 1:3
level3_better=level3_better[~level3_better.iloc[:,1:3].isnull().any(axis=1)]
level3_better.reset_index(drop=True, inplace=True)
level3_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1
1,116.0,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468,-3.0,113.0
2,117.0,Botswana,0.693,61.1409,12.265138,10.34,16198.31841,-43.0,110.0
3,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194,0.0,119.0
4,118.0,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831,26.0,121.0
5,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621,20.0,118.0
6,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
7,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
8,123.0,Belize,0.683,70.4697,12.99169,8.8476,6309.099778,6.0,120.0
9,123.0,Morocco,0.683,74.0419,14.15191,5.916,7302.81917,1.0,122.0
10,125.0,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889,-8.0,124.0
11,126.0,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595,6.0,129.0
12,127.0,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512,-15.0,125.0
13,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
14,129.0,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781,4.0,128.0
15,130.0,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899,-2.0,131.0
16,131.0,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393,12.0,131.0
17,132.0,India,0.633,67.2398,11.87462,6.655109,6589.980037,-6.0,130.0
18,133.0,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017,-2.0,135.0
19,134.0,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945,22.0,136.0
20,135.0,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317,-20.0,133.0
21,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
22,137.0,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301,-1.0,138.0
23,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
24,139.0,Namibia,0.615,59.269,11.927207,7.192013,8633.504452,-23.0,134.0
25,140.0,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617,-18.0,142.0
26,140.0,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435,7.0,140.0
27,140.0,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633,23.0,142.0
28,143.0,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444,10.0,144.0
29,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873,-21.0,141.0
30,145.0,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993,-47.0,147.0
31,146.0,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154,3.0,148.0
32,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
33,148.0,Angola,0.586,61.6434,12.1721,5.417391,5465.617791,-14.0,149.0
34,149.0,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234,5.0,145.0
35,150.0,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893,-2.0,152.0
36,151.0,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408,6.0,150.0
37,152.0,Kenya,0.575,61.427,10.698558,6.652,4473.570344,-6.0,150.0
38,153.0,Congo,0.571,63.5187,12.330815,6.166,2889.283521,11.0,153.0
39,154.0,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739,7.0,154.0
40,155.0,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362,13.0,155.0
41,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
42,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573,-4.0,157.0
43,158.0,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711,-20.0,158.0
44,159.0,CÃ´te d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516,-22.0,159.0

In [326]:
#Buscamos valores NO numericos de una fila
level3_better[level3_better.iloc[:, 2].str.contains('\D+').fillna(False)]

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,HDI rank.1

In [327]:
#Eliminamos la fila de cadenas
level3_better=level3_better[~level3_better.iloc[:, 2].str.contains('\D+').fillna(False)]
level3_better.reset_index(drop=True, inplace=True)
level3_better

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,116.0,Philippines,0.699,69.2664,13.12657,8.9691,8920.428468,-3.0,113.0
1,117.0,Botswana,0.693,61.1409,12.265138,10.34,16198.31841,-43.0,110.0
2,118.0,Bolivia (Plurinational State of),0.692,63.6304,14.946971,9.82775,8111.190194,0.0,119.0
3,118.0,Kyrgyzstan,0.692,69.9774,13.1953,11.374106,4566.303831,26.0,121.0
4,120.0,Venezuela (Bolivarian Republic of),0.691,70.5536,12.81608,11.107277,4810.882621,20.0,118.0
5,121.0,Iraq,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
6,122.0,Tajikistan,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
7,123.0,Belize,0.683,70.4697,12.99169,8.8476,6309.099778,6.0,120.0
8,123.0,Morocco,0.683,74.0419,14.15191,5.916,7302.81917,1.0,122.0
9,125.0,El Salvador,0.675,70.7479,12.671348,7.15093,8295.665889,-8.0,124.0
10,126.0,Nicaragua,0.667,73.8368,12.641358,7.144,5624.793595,6.0,129.0
11,127.0,Bhutan,0.666,71.815,13.225005,5.170262,9437.541512,-15.0,125.0
12,128.0,Cabo Verde,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
13,129.0,Bangladesh,0.661,72.3811,12.44198,7.37906,5472.104781,4.0,128.0
14,130.0,Tuvalu,0.641,64.5466,9.40443,10.573108,6351.435899,-2.0,131.0
15,131.0,Marshall Islands,0.639,65.2688,10.23932,10.88314,4619.535393,12.0,131.0
16,132.0,India,0.633,67.2398,11.87462,6.655109,6589.980037,-6.0,130.0
17,133.0,Ghana,0.632,63.7954,12.04778,8.329887,5744.504017,-2.0,135.0
18,134.0,Micronesia (Federated States of),0.628,70.71,11.54948,7.804956,3696.173945,22.0,136.0
19,135.0,Guatemala,0.627,69.2368,10.56245,5.6813,8723.285317,-20.0,133.0
20,136.0,Kiribati,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
21,137.0,Honduras,0.621,70.1229,10.132814,7.08848,5297.955301,-1.0,138.0
22,138.0,Sao Tome and Principe,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
23,139.0,Namibia,0.615,59.269,11.927207,7.192013,8633.504452,-23.0,134.0
24,140.0,Lao People's Democratic Republic,0.607,68.0608,10.13611,5.374,7699.579617,-18.0,142.0
25,140.0,Timor-Leste,0.607,67.7369,12.616098,5.43679,4460.869435,7.0,140.0
26,140.0,Vanuatu,0.607,70.449,11.535315,7.064846,3085.411633,23.0,142.0
27,143.0,Nepal,0.602,68.4495,12.88695,5.121793,3877.315444,10.0,144.0
28,144.0,Eswatini (Kingdom of),0.597,57.0657,13.744346,5.596,7678.591873,-21.0,141.0
29,145.0,Equatorial Guinea,0.596,60.5943,9.73494,5.910863,12073.95993,-47.0,147.0
30,146.0,Cambodia,0.593,69.5835,11.46772,5.088,4078.697154,3.0,148.0
31,146.0,Zimbabwe,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
32,148.0,Angola,0.586,61.6434,12.1721,5.417391,5465.617791,-14.0,149.0
33,149.0,Myanmar,0.585,65.6716,10.909138,6.3768,3850.524234,5.0,145.0
34,150.0,Syrian Arab Republic,0.577,72.0627,9.16422,5.1,4191.933893,-2.0,152.0
35,151.0,Cameroon,0.576,60.3334,13.108599,6.15131,3620.932408,6.0,150.0
36,152.0,Kenya,0.575,61.427,10.698558,6.652,4473.570344,-6.0,150.0
37,153.0,Congo,0.571,63.5187,12.330815,6.166,2889.283521,11.0,153.0
38,154.0,Zambia,0.565,61.2234,10.92876,7.187091,3217.767739,7.0,154.0
39,155.0,Solomon Islands,0.564,70.3477,10.32869,5.711848,2481.511362,13.0,155.0
40,156.0,Comoros,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
41,156.0,Papua New Guinea,0.558,65.3506,10.360771,4.74,4008.623573,-4.0,157.0
42,158.0,Mauritania,0.556,64.3636,9.37616,4.918805,5075.305711,-20.0,158.0
43,159.0,CÃ´te d'Ivoire,0.55,58.5983,10.67558,5.199139,5217.448516,-22.0,159.0

In [328]:
#Probar si existen valores nulos en la columna "Hdi_Rank"
level3_better[level3_better.Hdi_Rank.isnull()]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [329]:
#Ahora validando si existe alguna columna nula
level3_better[level3_better.isnull().any(axis=1)]

Empty DataFrame
Columns: [Hdi_Rank, Country, Human_Development_Index__2021, Life_Expectancy_At_Birth2021, Expected_Years_Of_Schooling2021, Mean_Years_Of_Schooling2021, Gross_National_Income__Per_Capita2021, Gni_Per_Capita_Rank_Minus_Hdi_Rank2021, Hdi_Rank2020]
Index: []

In [330]:
#Validamos la calidad de nuestros datos
level3_better.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 9 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                44 non-null     object
 1   Country                                 44 non-null     object
 2   Human_Development_Index__2021           44 non-null     object
 3   Life_Expectancy_At_Birth2021            44 non-null     object
 4   Expected_Years_Of_Schooling2021         44 non-null     object
 5   Mean_Years_Of_Schooling2021             44 non-null     object
 6   Gross_National_Income__Per_Capita2021   44 non-null     object
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  44 non-null     object
 8   Hdi_Rank2020                            44 non-null     object
dtypes: object(9)
memory usage: 3.2+ KB

In [331]:
#Evaluamos si los elementos de la columna "Gross_National_Income__Per_Capita2021" son cadenas o textos
level3_better.iloc[:,6]

0     8920.428468
1     16198.31841
2     8111.190194
3     4566.303831
4     4810.882621
5     9977.249073
6     4547.742427
7     6309.099778
8      7302.81917
9     8295.665889
10    5624.793595
11    9437.541512
12    6230.200199
13    5472.104781
14    6351.435899
15    4619.535393
16    6589.980037
17    5744.504017
18    3696.173945
19    8723.285317
20    4062.586034
21    5297.955301
22    4021.350815
23    8633.504452
24    7699.579617
25    4460.869435
26    3085.411633
27    3877.315444
28    7678.591873
29    12073.95993
30    4078.697154
31    3809.887158
32    5465.617791
33    3850.524234
34    4191.933893
35    3620.932408
36    4473.570344
37    2889.283521
38    3217.767739
39    2481.511362
40    3142.064119
41    4008.623573
42    5075.305711
43    5217.448516
Name: Gross_National_Income__Per_Capita2021, dtype: object

In [332]:
#Vamos a transformar todas las columnas en numericos sin afectar a la columna "Country"
level3_clean=level3_better.set_index('Country')
level3_formatted=level3_clean.apply(pd.to_numeric)
level3_formatted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44 entries, Philippines to CÃ´te d'Ivoire
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                44 non-null     float64
 1   Human_Development_Index__2021           44 non-null     float64
 2   Life_Expectancy_At_Birth2021            44 non-null     float64
 3   Expected_Years_Of_Schooling2021         44 non-null     float64
 4   Mean_Years_Of_Schooling2021             44 non-null     float64
 5   Gross_National_Income__Per_Capita2021   44 non-null     float64
 6   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  44 non-null     float64
 7   Hdi_Rank2020                            44 non-null     float64
dtypes: float64(8)
memory usage: 3.1+ KB

In [333]:
#Devolvemos del indice a la columna "Country"
level3_formatted.reset_index(drop=False,inplace=True)
level3_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,Philippines,116.0,0.699,69.2664,13.126570,8.969100,8920.428468,-3.0,113.0
1,Botswana,117.0,0.693,61.1409,12.265138,10.340000,16198.318410,-43.0,110.0
2,Bolivia (Plurinational State of),118.0,0.692,63.6304,14.946971,9.827750,8111.190194,0.0,119.0
3,Kyrgyzstan,118.0,0.692,69.9774,13.195300,11.374106,4566.303831,26.0,121.0
4,Venezuela (Bolivarian Republic of),120.0,0.691,70.5536,12.816080,11.107277,4810.882621,20.0,118.0
5,Iraq,121.0,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
6,Tajikistan,122.0,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
7,Belize,123.0,0.683,70.4697,12.991690,8.847600,6309.099778,6.0,120.0
8,Morocco,123.0,0.683,74.0419,14.151910,5.916000,7302.819170,1.0,122.0
9,El Salvador,125.0,0.675,70.7479,12.671348,7.150930,8295.665889,-8.0,124.0
10,Nicaragua,126.0,0.667,73.8368,12.641358,7.144000,5624.793595,6.0,129.0
11,Bhutan,127.0,0.666,71.8150,13.225005,5.170262,9437.541512,-15.0,125.0
12,Cabo Verde,128.0,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
13,Bangladesh,129.0,0.661,72.3811,12.441980,7.379060,5472.104781,4.0,128.0
14,Tuvalu,130.0,0.641,64.5466,9.404430,10.573108,6351.435899,-2.0,131.0
15,Marshall Islands,131.0,0.639,65.2688,10.239320,10.883140,4619.535393,12.0,131.0
16,India,132.0,0.633,67.2398,11.874620,6.655109,6589.980037,-6.0,130.0
17,Ghana,133.0,0.632,63.7954,12.047780,8.329887,5744.504017,-2.0,135.0
18,Micronesia (Federated States of),134.0,0.628,70.7100,11.549480,7.804956,3696.173945,22.0,136.0
19,Guatemala,135.0,0.627,69.2368,10.562450,5.681300,8723.285317,-20.0,133.0
20,Kiribati,136.0,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
21,Honduras,137.0,0.621,70.1229,10.132814,7.088480,5297.955301,-1.0,138.0
22,Sao Tome and Principe,138.0,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
23,Namibia,139.0,0.615,59.2690,11.927207,7.192013,8633.504452,-23.0,134.0
24,Lao People's Democratic Republic,140.0,0.607,68.0608,10.136110,5.374000,7699.579617,-18.0,142.0
25,Timor-Leste,140.0,0.607,67.7369,12.616098,5.436790,4460.869435,7.0,140.0
26,Vanuatu,140.0,0.607,70.4490,11.535315,7.064846,3085.411633,23.0,142.0
27,Nepal,143.0,0.602,68.4495,12.886950,5.121793,3877.315444,10.0,144.0
28,Eswatini (Kingdom of),144.0,0.597,57.0657,13.744346,5.596000,7678.591873,-21.0,141.0
29,Equatorial Guinea,145.0,0.596,60.5943,9.734940,5.910863,12073.959930,-47.0,147.0
30,Cambodia,146.0,0.593,69.5835,11.467720,5.088000,4078.697154,3.0,148.0
31,Zimbabwe,146.0,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
32,Angola,148.0,0.586,61.6434,12.172100,5.417391,5465.617791,-14.0,149.0
33,Myanmar,149.0,0.585,65.6716,10.909138,6.376800,3850.524234,5.0,145.0
34,Syrian Arab Republic,150.0,0.577,72.0627,9.164220,5.100000,4191.933893,-2.0,152.0
35,Cameroon,151.0,0.576,60.3334,13.108599,6.151310,3620.932408,6.0,150.0
36,Kenya,152.0,0.575,61.4270,10.698558,6.652000,4473.570344,-6.0,150.0
37,Congo,153.0,0.571,63.5187,12.330815,6.166000,2889.283521,11.0,153.0
38,Zambia,154.0,0.565,61.2234,10.928760,7.187091,3217.767739,7.0,154.0
39,Solomon Islands,155.0,0.564,70.3477,10.328690,5.711848,2481.511362,13.0,155.0
40,Comoros,156.0,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
41,Papua New Guinea,156.0,0.558,65.3506,10.360771,4.740000,4008.623573,-4.0,157.0
42,Mauritania,158.0,0.556,64.3636,9.376160,4.918805,5075.305711,-20.0,158.0
43,CÃ´te d'Ivoire,159.0,0.550,58.5983,10.675580,5.199139,5217.448516,-22.0,159.0

In [334]:
#Colocamos en mayuscula los elementos de la columna "Country"
level3_formatted['Country']=level3_formatted.Country.str.strip()
level3_formatted['Country']=level3_formatted.Country.str.upper()
level3_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020
0,PHILIPPINES,116.0,0.699,69.2664,13.126570,8.969100,8920.428468,-3.0,113.0
1,BOTSWANA,117.0,0.693,61.1409,12.265138,10.340000,16198.318410,-43.0,110.0
2,BOLIVIA (PLURINATIONAL STATE OF),118.0,0.692,63.6304,14.946971,9.827750,8111.190194,0.0,119.0
3,KYRGYZSTAN,118.0,0.692,69.9774,13.195300,11.374106,4566.303831,26.0,121.0
4,VENEZUELA (BOLIVARIAN REPUBLIC OF),120.0,0.691,70.5536,12.816080,11.107277,4810.882621,20.0,118.0
5,IRAQ,121.0,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0
6,TAJIKISTAN,122.0,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0
7,BELIZE,123.0,0.683,70.4697,12.991690,8.847600,6309.099778,6.0,120.0
8,MOROCCO,123.0,0.683,74.0419,14.151910,5.916000,7302.819170,1.0,122.0
9,EL SALVADOR,125.0,0.675,70.7479,12.671348,7.150930,8295.665889,-8.0,124.0
10,NICARAGUA,126.0,0.667,73.8368,12.641358,7.144000,5624.793595,6.0,129.0
11,BHUTAN,127.0,0.666,71.8150,13.225005,5.170262,9437.541512,-15.0,125.0
12,CABO VERDE,128.0,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0
13,BANGLADESH,129.0,0.661,72.3811,12.441980,7.379060,5472.104781,4.0,128.0
14,TUVALU,130.0,0.641,64.5466,9.404430,10.573108,6351.435899,-2.0,131.0
15,MARSHALL ISLANDS,131.0,0.639,65.2688,10.239320,10.883140,4619.535393,12.0,131.0
16,INDIA,132.0,0.633,67.2398,11.874620,6.655109,6589.980037,-6.0,130.0
17,GHANA,133.0,0.632,63.7954,12.047780,8.329887,5744.504017,-2.0,135.0
18,MICRONESIA (FEDERATED STATES OF),134.0,0.628,70.7100,11.549480,7.804956,3696.173945,22.0,136.0
19,GUATEMALA,135.0,0.627,69.2368,10.562450,5.681300,8723.285317,-20.0,133.0
20,KIRIBATI,136.0,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0
21,HONDURAS,137.0,0.621,70.1229,10.132814,7.088480,5297.955301,-1.0,138.0
22,SAO TOME AND PRINCIPE,138.0,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0
23,NAMIBIA,139.0,0.615,59.2690,11.927207,7.192013,8633.504452,-23.0,134.0
24,LAO PEOPLE'S DEMOCRATIC REPUBLIC,140.0,0.607,68.0608,10.136110,5.374000,7699.579617,-18.0,142.0
25,TIMOR-LESTE,140.0,0.607,67.7369,12.616098,5.436790,4460.869435,7.0,140.0
26,VANUATU,140.0,0.607,70.4490,11.535315,7.064846,3085.411633,23.0,142.0
27,NEPAL,143.0,0.602,68.4495,12.886950,5.121793,3877.315444,10.0,144.0
28,ESWATINI (KINGDOM OF),144.0,0.597,57.0657,13.744346,5.596000,7678.591873,-21.0,141.0
29,EQUATORIAL GUINEA,145.0,0.596,60.5943,9.734940,5.910863,12073.959930,-47.0,147.0
30,CAMBODIA,146.0,0.593,69.5835,11.467720,5.088000,4078.697154,3.0,148.0
31,ZIMBABWE,146.0,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0
32,ANGOLA,148.0,0.586,61.6434,12.172100,5.417391,5465.617791,-14.0,149.0
33,MYANMAR,149.0,0.585,65.6716,10.909138,6.376800,3850.524234,5.0,145.0
34,SYRIAN ARAB REPUBLIC,150.0,0.577,72.0627,9.164220,5.100000,4191.933893,-2.0,152.0
35,CAMEROON,151.0,0.576,60.3334,13.108599,6.151310,3620.932408,6.0,150.0
36,KENYA,152.0,0.575,61.4270,10.698558,6.652000,4473.570344,-6.0,150.0
37,CONGO,153.0,0.571,63.5187,12.330815,6.166000,2889.283521,11.0,153.0
38,ZAMBIA,154.0,0.565,61.2234,10.928760,7.187091,3217.767739,7.0,154.0
39,SOLOMON ISLANDS,155.0,0.564,70.3477,10.328690,5.711848,2481.511362,13.0,155.0
40,COMOROS,156.0,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0
41,PAPUA NEW GUINEA,156.0,0.558,65.3506,10.360771,4.740000,4008.623573,-4.0,157.0
42,MAURITANIA,158.0,0.556,64.3636,9.376160,4.918805,5075.305711,-20.0,158.0
43,CÃ”TE D'IVOIRE,159.0,0.550,58.5983,10.675580,5.199139,5217.448516,-22.0,159.0

In [335]:
#Agregamos la columna de indicador de desarrollo
level3_formatted['Development'] = "MEDIUM HUMAN DEVELOPMENT"
level3_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,PHILIPPINES,116.0,0.699,69.2664,13.126570,8.969100,8920.428468,-3.0,113.0,MEDIUM HUMAN DEVELOPMENT
1,BOTSWANA,117.0,0.693,61.1409,12.265138,10.340000,16198.318410,-43.0,110.0,MEDIUM HUMAN DEVELOPMENT
2,BOLIVIA (PLURINATIONAL STATE OF),118.0,0.692,63.6304,14.946971,9.827750,8111.190194,0.0,119.0,MEDIUM HUMAN DEVELOPMENT
3,KYRGYZSTAN,118.0,0.692,69.9774,13.195300,11.374106,4566.303831,26.0,121.0,MEDIUM HUMAN DEVELOPMENT
4,VENEZUELA (BOLIVARIAN REPUBLIC OF),120.0,0.691,70.5536,12.816080,11.107277,4810.882621,20.0,118.0,MEDIUM HUMAN DEVELOPMENT
5,IRAQ,121.0,0.686,70.3779,12.087473,7.905593,9977.249073,-12.0,122.0,MEDIUM HUMAN DEVELOPMENT
6,TAJIKISTAN,122.0,0.685,71.5942,11.653036,11.333394,4547.742427,23.0,126.0,MEDIUM HUMAN DEVELOPMENT
7,BELIZE,123.0,0.683,70.4697,12.991690,8.847600,6309.099778,6.0,120.0,MEDIUM HUMAN DEVELOPMENT
8,MOROCCO,123.0,0.683,74.0419,14.151910,5.916000,7302.819170,1.0,122.0,MEDIUM HUMAN DEVELOPMENT
9,EL SALVADOR,125.0,0.675,70.7479,12.671348,7.150930,8295.665889,-8.0,124.0,MEDIUM HUMAN DEVELOPMENT
10,NICARAGUA,126.0,0.667,73.8368,12.641358,7.144000,5624.793595,6.0,129.0,MEDIUM HUMAN DEVELOPMENT
11,BHUTAN,127.0,0.666,71.8150,13.225005,5.170262,9437.541512,-15.0,125.0,MEDIUM HUMAN DEVELOPMENT
12,CABO VERDE,128.0,0.662,74.0518,12.554614,6.287719,6230.200199,2.0,127.0,MEDIUM HUMAN DEVELOPMENT
13,BANGLADESH,129.0,0.661,72.3811,12.441980,7.379060,5472.104781,4.0,128.0,MEDIUM HUMAN DEVELOPMENT
14,TUVALU,130.0,0.641,64.5466,9.404430,10.573108,6351.435899,-2.0,131.0,MEDIUM HUMAN DEVELOPMENT
15,MARSHALL ISLANDS,131.0,0.639,65.2688,10.239320,10.883140,4619.535393,12.0,131.0,MEDIUM HUMAN DEVELOPMENT
16,INDIA,132.0,0.633,67.2398,11.874620,6.655109,6589.980037,-6.0,130.0,MEDIUM HUMAN DEVELOPMENT
17,GHANA,133.0,0.632,63.7954,12.047780,8.329887,5744.504017,-2.0,135.0,MEDIUM HUMAN DEVELOPMENT
18,MICRONESIA (FEDERATED STATES OF),134.0,0.628,70.7100,11.549480,7.804956,3696.173945,22.0,136.0,MEDIUM HUMAN DEVELOPMENT
19,GUATEMALA,135.0,0.627,69.2368,10.562450,5.681300,8723.285317,-20.0,133.0,MEDIUM HUMAN DEVELOPMENT
20,KIRIBATI,136.0,0.624,67.4172,11.801993,7.984462,4062.586034,14.0,137.0,MEDIUM HUMAN DEVELOPMENT
21,HONDURAS,137.0,0.621,70.1229,10.132814,7.088480,5297.955301,-1.0,138.0,MEDIUM HUMAN DEVELOPMENT
22,SAO TOME AND PRINCIPE,138.0,0.618,67.5912,13.365385,6.215599,4021.350815,13.0,139.0,MEDIUM HUMAN DEVELOPMENT
23,NAMIBIA,139.0,0.615,59.2690,11.927207,7.192013,8633.504452,-23.0,134.0,MEDIUM HUMAN DEVELOPMENT
24,LAO PEOPLE'S DEMOCRATIC REPUBLIC,140.0,0.607,68.0608,10.136110,5.374000,7699.579617,-18.0,142.0,MEDIUM HUMAN DEVELOPMENT
25,TIMOR-LESTE,140.0,0.607,67.7369,12.616098,5.436790,4460.869435,7.0,140.0,MEDIUM HUMAN DEVELOPMENT
26,VANUATU,140.0,0.607,70.4490,11.535315,7.064846,3085.411633,23.0,142.0,MEDIUM HUMAN DEVELOPMENT
27,NEPAL,143.0,0.602,68.4495,12.886950,5.121793,3877.315444,10.0,144.0,MEDIUM HUMAN DEVELOPMENT
28,ESWATINI (KINGDOM OF),144.0,0.597,57.0657,13.744346,5.596000,7678.591873,-21.0,141.0,MEDIUM HUMAN DEVELOPMENT
29,EQUATORIAL GUINEA,145.0,0.596,60.5943,9.734940,5.910863,12073.959930,-47.0,147.0,MEDIUM HUMAN DEVELOPMENT
30,CAMBODIA,146.0,0.593,69.5835,11.467720,5.088000,4078.697154,3.0,148.0,MEDIUM HUMAN DEVELOPMENT
31,ZIMBABWE,146.0,0.593,59.2531,12.110969,8.710909,3809.887158,9.0,145.0,MEDIUM HUMAN DEVELOPMENT
32,ANGOLA,148.0,0.586,61.6434,12.172100,5.417391,5465.617791,-14.0,149.0,MEDIUM HUMAN DEVELOPMENT
33,MYANMAR,149.0,0.585,65.6716,10.909138,6.376800,3850.524234,5.0,145.0,MEDIUM HUMAN DEVELOPMENT
34,SYRIAN ARAB REPUBLIC,150.0,0.577,72.0627,9.164220,5.100000,4191.933893,-2.0,152.0,MEDIUM HUMAN DEVELOPMENT
35,CAMEROON,151.0,0.576,60.3334,13.108599,6.151310,3620.932408,6.0,150.0,MEDIUM HUMAN DEVELOPMENT
36,KENYA,152.0,0.575,61.4270,10.698558,6.652000,4473.570344,-6.0,150.0,MEDIUM HUMAN DEVELOPMENT
37,CONGO,153.0,0.571,63.5187,12.330815,6.166000,2889.283521,11.0,153.0,MEDIUM HUMAN DEVELOPMENT
38,ZAMBIA,154.0,0.565,61.2234,10.928760,7.187091,3217.767739,7.0,154.0,MEDIUM HUMAN DEVELOPMENT
39,SOLOMON ISLANDS,155.0,0.564,70.3477,10.328690,5.711848,2481.511362,13.0,155.0,MEDIUM HUMAN DEVELOPMENT
40,COMOROS,156.0,0.558,63.4174,11.924324,5.078649,3142.064119,6.0,156.0,MEDIUM HUMAN DEVELOPMENT
41,PAPUA NEW GUINEA,156.0,0.558,65.3506,10.360771,4.740000,4008.623573,-4.0,157.0,MEDIUM HUMAN DEVELOPMENT
42,MAURITANIA,158.0,0.556,64.3636,9.376160,4.918805,5075.305711,-20.0,158.0,MEDIUM HUMAN DEVELOPMENT
43,CÃ”TE D'IVOIRE,159.0,0.550,58.5983,10.675580,5.199139,5217.448516,-22.0,159.0,MEDIUM HUMAN DEVELOPMENT

In [336]:
#Leemos el cuarto archivo de excel Level4
level4=pd.read_excel(append_data_path+"/level4.xlsx")

In [337]:
level4

,HDI rank,Country,Unnamed: 2,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank,le
0,160,Tanzania (United Republic of),LOW HUMAN DEVELOPMENT,0.549,66.2007,9.221490,6.372899,2664.329096,7,NaN
1,161,Pakistan,LOW HUMAN DEVELOPMENT,0.544,66.0979,8.658350,4.536330,4623.705430,-19,NaN
2,162,Togo,LOW HUMAN DEVELOPMENT,0.539,61.6194,12.950494,5.016807,2166.619062,12,NaN
3,163,Haiti,LOW HUMAN DEVELOPMENT,0.535,63.1924,9.700000,5.554000,2847.500746,2,NaN
4,163,Nigeria,LOW HUMAN DEVELOPMENT,0.535,52.6760,10.127584,7.181074,4790.284425,-22,NaN
5,165,Rwanda,LOW HUMAN DEVELOPMENT,0.534,66.0722,11.230970,4.425292,2209.795202,6,NaN
6,166,Benin,LOW HUMAN DEVELOPMENT,0.525,59.8210,10.766680,4.304786,3408.965923,-7,NaN
7,166,Uganda,LOW HUMAN DEVELOPMENT,0.525,62.7048,10.149870,5.730942,2181.436510,6,NaN
8,168,Lesotho,LOW HUMAN DEVELOPMENT,0.514,53.0620,12.040878,6.010185,2700.435748,-2,NaN
9,169,Malawi,LOW HUMAN DEVELOPMENT,0.512,62.9044,12.678985,4.489695,1465.635064,13,NaN
10,170,Senegal,LOW HUMAN DEVELOPMENT,0.511,67.0926,8.963750,2.937938,3344.311825,-10,NaN
11,171,Djibouti,LOW HUMAN DEVELOPMENT,0.509,62.3049,7.432980,4.100000,5024.993944,-32,NaN
12,172,Sudan,LOW HUMAN DEVELOPMENT,0.508,65.2667,7.945188,3.820000,3575.190840,-14,NaN
13,173,Madagascar,LOW HUMAN DEVELOPMENT,0.501,64.4853,10.134991,5.120469,1483.520983,8,NaN
14,174,Gambia,LOW HUMAN DEVELOPMENT,0.500,62.0830,9.418626,4.637487,2172.207664,-1,NaN
15,175,Ethiopia,LOW HUMAN DEVELOPMENT,0.498,64.9748,9.651071,3.201521,2361.069604,-5,NaN
16,176,Eritrea,LOW HUMAN DEVELOPMENT,0.492,66.5358,8.064525,4.887235,1728.742667,3,NaN
17,177,Guinea-Bissau,LOW HUMAN DEVELOPMENT,0.483,59.6523,10.613063,3.583719,1908.241590,0,NaN
18,178,Liberia,LOW HUMAN DEVELOPMENT,0.481,60.7472,10.420790,5.082000,1288.742350,7,NaN
19,179,Congo (Democratic Republic of the),LOW HUMAN DEVELOPMENT,0.479,59.1930,9.817864,7.018697,1076.098781,9,NaN
20,180,Afghanistan,LOW HUMAN DEVELOPMENT,0.478,61.9824,10.263844,2.985070,1824.190915,-2,NaN
21,181,Sierra Leone,LOW HUMAN DEVELOPMENT,0.477,60.0624,9.573391,4.576081,1621.512579,-1,NaN
22,182,Guinea,LOW HUMAN DEVELOPMENT,0.465,58.8922,9.805297,2.202126,2480.887182,-13,NaN
23,183,Yemen,LOW HUMAN DEVELOPMENT,0.455,63.7534,9.098710,3.200000,1314.270189,1,NaN
24,184,Burkina Faso,LOW HUMAN DEVELOPMENT,0.449,59.2696,9.142100,2.114962,2117.915916,-8,NaN
25,185,Mozambique,LOW HUMAN DEVELOPMENT,0.446,59.3247,10.219152,3.197642,1198.073924,2,NaN
26,186,Mali,LOW HUMAN DEVELOPMENT,0.428,58.9414,7.423038,2.310000,2132.629443,-11,NaN
27,187,Burundi,LOW HUMAN DEVELOPMENT,0.426,61.6627,10.722722,3.129267,731.786709,4,NaN
28,188,Central African Republic,LOW HUMAN DEVELOPMENT,0.404,53.8947,8.040172,4.334000,966.058611,1,NaN
29,189,Niger,LOW HUMAN DEVELOPMENT,0.400,61.5763,6.957112,2.116717,1239.866936,-3,NaN
30,190,Chad,LOW HUMAN DEVELOPMENT,0.394,52.5254,8.035914,2.573774,1364.169417,-7,NaN
31,191,South Sudan,LOW HUMAN DEVELOPMENT,0.385,54.9752,5.542510,5.726140,767.787000,-1,NaN

In [338]:
#Analizamos la tabla y notamos que las cabeceras "Unnamed" no aportan informacion
level4 = level4.loc[:, ~level4.columns.str.startswith('Unnamed')]

In [339]:
#Verificamos si hay columnas con valores nulos
level4[level4.isnull().all(axis=1)]

Empty DataFrame
Columns: [HDI rank, Country, Human Development Index (HDI) , Life expectancy at birth, Expected years of schooling, Mean years of schooling, Gross national income (GNI) per capita, GNI per capita rank minus HDI rank, le]
Index: []

In [340]:
#Eliminamos la columna "le" porque no tiene informacion que aporte
level4 = level4.drop('le', axis=1)
level4

,HDI rank,Country,Human Development Index (HDI),Life expectancy at birth,Expected years of schooling,Mean years of schooling,Gross national income (GNI) per capita,GNI per capita rank minus HDI rank
0,160,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096,7
1,161,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,162,Togo,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,163,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,163,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425,-22
5,165,Rwanda,0.534,66.0722,11.230970,4.425292,2209.795202,6
6,166,Benin,0.525,59.8210,10.766680,4.304786,3408.965923,-7
7,166,Uganda,0.525,62.7048,10.149870,5.730942,2181.436510,6
8,168,Lesotho,0.514,53.0620,12.040878,6.010185,2700.435748,-2
9,169,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064,13
10,170,Senegal,0.511,67.0926,8.963750,2.937938,3344.311825,-10
11,171,Djibouti,0.509,62.3049,7.432980,4.100000,5024.993944,-32
12,172,Sudan,0.508,65.2667,7.945188,3.820000,3575.190840,-14
13,173,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983,8
14,174,Gambia,0.500,62.0830,9.418626,4.637487,2172.207664,-1
15,175,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604,-5
16,176,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667,3
17,177,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.241590,0
18,178,Liberia,0.481,60.7472,10.420790,5.082000,1288.742350,7
19,179,Congo (Democratic Republic of the),0.479,59.1930,9.817864,7.018697,1076.098781,9
20,180,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915,-2
21,181,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579,-1
22,182,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182,-13
23,183,Yemen,0.455,63.7534,9.098710,3.200000,1314.270189,1
24,184,Burkina Faso,0.449,59.2696,9.142100,2.114962,2117.915916,-8
25,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,2
26,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443,-11
27,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4
28,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1
29,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3
30,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7
31,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1

In [341]:
#Le agregamos el aÃ±o a las columnas en el rango (2,8)
for a in range(2, 8):
    level4.columns.values[a] = level4.columns.values[a] + "2021"
level4

,HDI rank,Country,Human Development Index (HDI) 2021,Life expectancy at birth2021,Expected years of schooling2021,Mean years of schooling2021,Gross national income (GNI) per capita2021,GNI per capita rank minus HDI rank2021
0,160,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096,7
1,161,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,162,Togo,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,163,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,163,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425,-22
5,165,Rwanda,0.534,66.0722,11.230970,4.425292,2209.795202,6
6,166,Benin,0.525,59.8210,10.766680,4.304786,3408.965923,-7
7,166,Uganda,0.525,62.7048,10.149870,5.730942,2181.436510,6
8,168,Lesotho,0.514,53.0620,12.040878,6.010185,2700.435748,-2
9,169,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064,13
10,170,Senegal,0.511,67.0926,8.963750,2.937938,3344.311825,-10
11,171,Djibouti,0.509,62.3049,7.432980,4.100000,5024.993944,-32
12,172,Sudan,0.508,65.2667,7.945188,3.820000,3575.190840,-14
13,173,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983,8
14,174,Gambia,0.500,62.0830,9.418626,4.637487,2172.207664,-1
15,175,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604,-5
16,176,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667,3
17,177,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.241590,0
18,178,Liberia,0.481,60.7472,10.420790,5.082000,1288.742350,7
19,179,Congo (Democratic Republic of the),0.479,59.1930,9.817864,7.018697,1076.098781,9
20,180,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915,-2
21,181,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579,-1
22,182,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182,-13
23,183,Yemen,0.455,63.7534,9.098710,3.200000,1314.270189,1
24,184,Burkina Faso,0.449,59.2696,9.142100,2.114962,2117.915916,-8
25,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,2
26,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443,-11
27,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4
28,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1
29,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3
30,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7
31,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1

In [342]:
#Visualizamos el reemplazo los parentesis y espacios por "_"
level4.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)

Index(['Hdi_Rank', 'Country', 'Human_Development_Index__2021',
       'Life_Expectancy_At_Birth2021', 'Expected_Years_Of_Schooling2021',
       'Mean_Years_Of_Schooling2021', 'Gross_National_Income__Per_Capita2021',
       'Gni_Per_Capita_Rank_Minus_Hdi_Rank2021'],
      dtype='object')

In [343]:
#Reemplazamos los parentesis y espacios por "_"
level4.columns=level4.columns.str.replace('\(\w*\s*\w*\W*\)','',regex=True).str.title().str.replace("\s","_",regex=True)
level4

,Hdi_Rank,Country,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021
0,160,Tanzania (United Republic of),0.549,66.2007,9.221490,6.372899,2664.329096,7
1,161,Pakistan,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,162,Togo,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,163,Haiti,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,163,Nigeria,0.535,52.6760,10.127584,7.181074,4790.284425,-22
5,165,Rwanda,0.534,66.0722,11.230970,4.425292,2209.795202,6
6,166,Benin,0.525,59.8210,10.766680,4.304786,3408.965923,-7
7,166,Uganda,0.525,62.7048,10.149870,5.730942,2181.436510,6
8,168,Lesotho,0.514,53.0620,12.040878,6.010185,2700.435748,-2
9,169,Malawi,0.512,62.9044,12.678985,4.489695,1465.635064,13
10,170,Senegal,0.511,67.0926,8.963750,2.937938,3344.311825,-10
11,171,Djibouti,0.509,62.3049,7.432980,4.100000,5024.993944,-32
12,172,Sudan,0.508,65.2667,7.945188,3.820000,3575.190840,-14
13,173,Madagascar,0.501,64.4853,10.134991,5.120469,1483.520983,8
14,174,Gambia,0.500,62.0830,9.418626,4.637487,2172.207664,-1
15,175,Ethiopia,0.498,64.9748,9.651071,3.201521,2361.069604,-5
16,176,Eritrea,0.492,66.5358,8.064525,4.887235,1728.742667,3
17,177,Guinea-Bissau,0.483,59.6523,10.613063,3.583719,1908.241590,0
18,178,Liberia,0.481,60.7472,10.420790,5.082000,1288.742350,7
19,179,Congo (Democratic Republic of the),0.479,59.1930,9.817864,7.018697,1076.098781,9
20,180,Afghanistan,0.478,61.9824,10.263844,2.985070,1824.190915,-2
21,181,Sierra Leone,0.477,60.0624,9.573391,4.576081,1621.512579,-1
22,182,Guinea,0.465,58.8922,9.805297,2.202126,2480.887182,-13
23,183,Yemen,0.455,63.7534,9.098710,3.200000,1314.270189,1
24,184,Burkina Faso,0.449,59.2696,9.142100,2.114962,2117.915916,-8
25,185,Mozambique,0.446,59.3247,10.219152,3.197642,1198.073924,2
26,186,Mali,0.428,58.9414,7.423038,2.310000,2132.629443,-11
27,187,Burundi,0.426,61.6627,10.722722,3.129267,731.786709,4
28,188,Central African Republic,0.404,53.8947,8.040172,4.334000,966.058611,1
29,189,Niger,0.400,61.5763,6.957112,2.116717,1239.866936,-3
30,190,Chad,0.394,52.5254,8.035914,2.573774,1364.169417,-7
31,191,South Sudan,0.385,54.9752,5.542510,5.726140,767.787000,-1

In [344]:
#Hacemos una copia del df y analizamos la existencia de valores nulos
level4_better=level4.copy()
level4_better.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                32 non-null     int64
 1   Country                                 32 non-null     object
 2   Human_Development_Index__2021           32 non-null     float64
 3   Life_Expectancy_At_Birth2021            32 non-null     float64
 4   Expected_Years_Of_Schooling2021         32 non-null     float64
 5   Mean_Years_Of_Schooling2021             32 non-null     float64
 6   Gross_National_Income__Per_Capita2021   32 non-null     float64
 7   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  32 non-null     int64
dtypes: float64(5), int64(2), object(1)
memory usage: 2.1+ KB

In [345]:
#Vamos a transformar todas las columnas en numericos sin afectar a la columna "Country"
level4_clean=level4_better.set_index('Country')
level4_formatted=level4_clean.apply(pd.to_numeric)
level4_formatted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 32 entries, Tanzania (United Republic of) to South Sudan
Data columns (total 7 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Hdi_Rank                                32 non-null     int64
 1   Human_Development_Index__2021           32 non-null     float64
 2   Life_Expectancy_At_Birth2021            32 non-null     float64
 3   Expected_Years_Of_Schooling2021         32 non-null     float64
 4   Mean_Years_Of_Schooling2021             32 non-null     float64
 5   Gross_National_Income__Per_Capita2021   32 non-null     float64
 6   Gni_Per_Capita_Rank_Minus_Hdi_Rank2021  32 non-null     int64
dtypes: float64(5), int64(2)
memory usage: 2.0+ KB

In [346]:
#Devolvemos del indice a la columna "Country"
level4_formatted.reset_index(drop=False,inplace=True)
level4_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021
0,Tanzania (United Republic of),160,0.549,66.2007,9.221490,6.372899,2664.329096,7
1,Pakistan,161,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,Togo,162,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,Haiti,163,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,Nigeria,163,0.535,52.6760,10.127584,7.181074,4790.284425,-22
5,Rwanda,165,0.534,66.0722,11.230970,4.425292,2209.795202,6
6,Benin,166,0.525,59.8210,10.766680,4.304786,3408.965923,-7
7,Uganda,166,0.525,62.7048,10.149870,5.730942,2181.436510,6
8,Lesotho,168,0.514,53.0620,12.040878,6.010185,2700.435748,-2
9,Malawi,169,0.512,62.9044,12.678985,4.489695,1465.635064,13
10,Senegal,170,0.511,67.0926,8.963750,2.937938,3344.311825,-10
11,Djibouti,171,0.509,62.3049,7.432980,4.100000,5024.993944,-32
12,Sudan,172,0.508,65.2667,7.945188,3.820000,3575.190840,-14
13,Madagascar,173,0.501,64.4853,10.134991,5.120469,1483.520983,8
14,Gambia,174,0.500,62.0830,9.418626,4.637487,2172.207664,-1
15,Ethiopia,175,0.498,64.9748,9.651071,3.201521,2361.069604,-5
16,Eritrea,176,0.492,66.5358,8.064525,4.887235,1728.742667,3
17,Guinea-Bissau,177,0.483,59.6523,10.613063,3.583719,1908.241590,0
18,Liberia,178,0.481,60.7472,10.420790,5.082000,1288.742350,7
19,Congo (Democratic Republic of the),179,0.479,59.1930,9.817864,7.018697,1076.098781,9
20,Afghanistan,180,0.478,61.9824,10.263844,2.985070,1824.190915,-2
21,Sierra Leone,181,0.477,60.0624,9.573391,4.576081,1621.512579,-1
22,Guinea,182,0.465,58.8922,9.805297,2.202126,2480.887182,-13
23,Yemen,183,0.455,63.7534,9.098710,3.200000,1314.270189,1
24,Burkina Faso,184,0.449,59.2696,9.142100,2.114962,2117.915916,-8
25,Mozambique,185,0.446,59.3247,10.219152,3.197642,1198.073924,2
26,Mali,186,0.428,58.9414,7.423038,2.310000,2132.629443,-11
27,Burundi,187,0.426,61.6627,10.722722,3.129267,731.786709,4
28,Central African Republic,188,0.404,53.8947,8.040172,4.334000,966.058611,1
29,Niger,189,0.400,61.5763,6.957112,2.116717,1239.866936,-3
30,Chad,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7
31,South Sudan,191,0.385,54.9752,5.542510,5.726140,767.787000,-1

In [347]:
#Colocamos en mayuscula los elementos de la columna "Country"
level4_formatted['Country']=level4_formatted.Country.str.strip()
level4_formatted['Country']=level4_formatted.Country.str.upper()
level4_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021
0,TANZANIA (UNITED REPUBLIC OF),160,0.549,66.2007,9.221490,6.372899,2664.329096,7
1,PAKISTAN,161,0.544,66.0979,8.658350,4.536330,4623.705430,-19
2,TOGO,162,0.539,61.6194,12.950494,5.016807,2166.619062,12
3,HAITI,163,0.535,63.1924,9.700000,5.554000,2847.500746,2
4,NIGERIA,163,0.535,52.6760,10.127584,7.181074,4790.284425,-22
5,RWANDA,165,0.534,66.0722,11.230970,4.425292,2209.795202,6
6,BENIN,166,0.525,59.8210,10.766680,4.304786,3408.965923,-7
7,UGANDA,166,0.525,62.7048,10.149870,5.730942,2181.436510,6
8,LESOTHO,168,0.514,53.0620,12.040878,6.010185,2700.435748,-2
9,MALAWI,169,0.512,62.9044,12.678985,4.489695,1465.635064,13
10,SENEGAL,170,0.511,67.0926,8.963750,2.937938,3344.311825,-10
11,DJIBOUTI,171,0.509,62.3049,7.432980,4.100000,5024.993944,-32
12,SUDAN,172,0.508,65.2667,7.945188,3.820000,3575.190840,-14
13,MADAGASCAR,173,0.501,64.4853,10.134991,5.120469,1483.520983,8
14,GAMBIA,174,0.500,62.0830,9.418626,4.637487,2172.207664,-1
15,ETHIOPIA,175,0.498,64.9748,9.651071,3.201521,2361.069604,-5
16,ERITREA,176,0.492,66.5358,8.064525,4.887235,1728.742667,3
17,GUINEA-BISSAU,177,0.483,59.6523,10.613063,3.583719,1908.241590,0
18,LIBERIA,178,0.481,60.7472,10.420790,5.082000,1288.742350,7
19,CONGO (DEMOCRATIC REPUBLIC OF THE),179,0.479,59.1930,9.817864,7.018697,1076.098781,9
20,AFGHANISTAN,180,0.478,61.9824,10.263844,2.985070,1824.190915,-2
21,SIERRA LEONE,181,0.477,60.0624,9.573391,4.576081,1621.512579,-1
22,GUINEA,182,0.465,58.8922,9.805297,2.202126,2480.887182,-13
23,YEMEN,183,0.455,63.7534,9.098710,3.200000,1314.270189,1
24,BURKINA FASO,184,0.449,59.2696,9.142100,2.114962,2117.915916,-8
25,MOZAMBIQUE,185,0.446,59.3247,10.219152,3.197642,1198.073924,2
26,MALI,186,0.428,58.9414,7.423038,2.310000,2132.629443,-11
27,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4
28,CENTRAL AFRICAN REPUBLIC,188,0.404,53.8947,8.040172,4.334000,966.058611,1
29,NIGER,189,0.400,61.5763,6.957112,2.116717,1239.866936,-3
30,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7
31,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1

In [348]:
#Agregamos la columna de indicador de desarrollo
level4_formatted['Development'] = "LOW HUMAN DEVELOPMENT"
level4_formatted

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Development
0,TANZANIA (UNITED REPUBLIC OF),160,0.549,66.2007,9.221490,6.372899,2664.329096,7,LOW HUMAN DEVELOPMENT
1,PAKISTAN,161,0.544,66.0979,8.658350,4.536330,4623.705430,-19,LOW HUMAN DEVELOPMENT
2,TOGO,162,0.539,61.6194,12.950494,5.016807,2166.619062,12,LOW HUMAN DEVELOPMENT
3,HAITI,163,0.535,63.1924,9.700000,5.554000,2847.500746,2,LOW HUMAN DEVELOPMENT
4,NIGERIA,163,0.535,52.6760,10.127584,7.181074,4790.284425,-22,LOW HUMAN DEVELOPMENT
5,RWANDA,165,0.534,66.0722,11.230970,4.425292,2209.795202,6,LOW HUMAN DEVELOPMENT
6,BENIN,166,0.525,59.8210,10.766680,4.304786,3408.965923,-7,LOW HUMAN DEVELOPMENT
7,UGANDA,166,0.525,62.7048,10.149870,5.730942,2181.436510,6,LOW HUMAN DEVELOPMENT
8,LESOTHO,168,0.514,53.0620,12.040878,6.010185,2700.435748,-2,LOW HUMAN DEVELOPMENT
9,MALAWI,169,0.512,62.9044,12.678985,4.489695,1465.635064,13,LOW HUMAN DEVELOPMENT
10,SENEGAL,170,0.511,67.0926,8.963750,2.937938,3344.311825,-10,LOW HUMAN DEVELOPMENT
11,DJIBOUTI,171,0.509,62.3049,7.432980,4.100000,5024.993944,-32,LOW HUMAN DEVELOPMENT
12,SUDAN,172,0.508,65.2667,7.945188,3.820000,3575.190840,-14,LOW HUMAN DEVELOPMENT
13,MADAGASCAR,173,0.501,64.4853,10.134991,5.120469,1483.520983,8,LOW HUMAN DEVELOPMENT
14,GAMBIA,174,0.500,62.0830,9.418626,4.637487,2172.207664,-1,LOW HUMAN DEVELOPMENT
15,ETHIOPIA,175,0.498,64.9748,9.651071,3.201521,2361.069604,-5,LOW HUMAN DEVELOPMENT
16,ERITREA,176,0.492,66.5358,8.064525,4.887235,1728.742667,3,LOW HUMAN DEVELOPMENT
17,GUINEA-BISSAU,177,0.483,59.6523,10.613063,3.583719,1908.241590,0,LOW HUMAN DEVELOPMENT
18,LIBERIA,178,0.481,60.7472,10.420790,5.082000,1288.742350,7,LOW HUMAN DEVELOPMENT
19,CONGO (DEMOCRATIC REPUBLIC OF THE),179,0.479,59.1930,9.817864,7.018697,1076.098781,9,LOW HUMAN DEVELOPMENT
20,AFGHANISTAN,180,0.478,61.9824,10.263844,2.985070,1824.190915,-2,LOW HUMAN DEVELOPMENT
21,SIERRA LEONE,181,0.477,60.0624,9.573391,4.576081,1621.512579,-1,LOW HUMAN DEVELOPMENT
22,GUINEA,182,0.465,58.8922,9.805297,2.202126,2480.887182,-13,LOW HUMAN DEVELOPMENT
23,YEMEN,183,0.455,63.7534,9.098710,3.200000,1314.270189,1,LOW HUMAN DEVELOPMENT
24,BURKINA FASO,184,0.449,59.2696,9.142100,2.114962,2117.915916,-8,LOW HUMAN DEVELOPMENT
25,MOZAMBIQUE,185,0.446,59.3247,10.219152,3.197642,1198.073924,2,LOW HUMAN DEVELOPMENT
26,MALI,186,0.428,58.9414,7.423038,2.310000,2132.629443,-11,LOW HUMAN DEVELOPMENT
27,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4,LOW HUMAN DEVELOPMENT
28,CENTRAL AFRICAN REPUBLIC,188,0.404,53.8947,8.040172,4.334000,966.058611,1,LOW HUMAN DEVELOPMENT
29,NIGER,189,0.400,61.5763,6.957112,2.116717,1239.866936,-3,LOW HUMAN DEVELOPMENT
30,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7,LOW HUMAN DEVELOPMENT
31,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1,LOW HUMAN DEVELOPMENT

In [349]:
#Realizamos la concatenacion de las 4 tablas. Coinciden en columnas
result = pd.concat([level1_formatted, level2_formatted, level3_formatted, level4_formatted], ignore_index=True)
result

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,SWITZERLAND,1.0,0.962,83.9872,16.500299,13.859660,66933.004540,5.0,3.0,VERY HIGH HUMAN DEVELOPMENT
1,NORWAY,2.0,0.961,83.2339,18.185200,13.003630,64660.106220,6.0,1.0,VERY HIGH HUMAN DEVELOPMENT
2,ICELAND,3.0,0.959,82.6782,19.163059,13.767170,55782.049810,11.0,2.0,VERY HIGH HUMAN DEVELOPMENT
3,"HONG KONG, CHINA (SAR)",4.0,0.952,85.4734,17.278170,12.226210,62606.845400,6.0,4.0,VERY HIGH HUMAN DEVELOPMENT
4,AUSTRALIA,5.0,0.951,84.5265,21.054590,12.726820,49238.433350,18.0,5.0,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
186,BURUNDI,187.0,0.426,61.6627,10.722722,3.129267,731.786709,4.0,NaN,LOW HUMAN DEVELOPMENT
187,CENTRAL AFRICAN REPUBLIC,188.0,0.404,53.8947,8.040172,4.334000,966.058611,1.0,NaN,LOW HUMAN DEVELOPMENT
188,NIGER,189.0,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0,NaN,LOW HUMAN DEVELOPMENT
189,CHAD,190.0,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,NaN,LOW HUMAN DEVELOPMENT
190,SOUTH SUDAN,191.0,0.385,54.9752,5.542510,5.726140,767.787000,-1.0,NaN,LOW HUMAN DEVELOPMENT

In [350]:
#Cambiamos el tipo de dato de la columna "Hdi_Rank" para mejor apreciacion
result['Hdi_Rank'] = result['Hdi_Rank'].astype(int)
result

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.859660,66933.004540,5.0,3.0,VERY HIGH HUMAN DEVELOPMENT
1,NORWAY,2,0.961,83.2339,18.185200,13.003630,64660.106220,6.0,1.0,VERY HIGH HUMAN DEVELOPMENT
2,ICELAND,3,0.959,82.6782,19.163059,13.767170,55782.049810,11.0,2.0,VERY HIGH HUMAN DEVELOPMENT
3,"HONG KONG, CHINA (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,6.0,4.0,VERY HIGH HUMAN DEVELOPMENT
4,AUSTRALIA,5,0.951,84.5265,21.054590,12.726820,49238.433350,18.0,5.0,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
186,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4.0,NaN,LOW HUMAN DEVELOPMENT
187,CENTRAL AFRICAN REPUBLIC,188,0.404,53.8947,8.040172,4.334000,966.058611,1.0,NaN,LOW HUMAN DEVELOPMENT
188,NIGER,189,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0,NaN,LOW HUMAN DEVELOPMENT
189,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,NaN,LOW HUMAN DEVELOPMENT
190,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1.0,NaN,LOW HUMAN DEVELOPMENT

In [351]:
#Aplicamos la misma logica para "Hdi_Rank2020" pero pasamos los valores nulos a "0" para comodidades de transformacion
result['Hdi_Rank2020'].fillna(0, inplace=True)
result['Hdi_Rank2020'] = result['Hdi_Rank2020'].astype(int)
result

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.859660,66933.004540,5.0,3,VERY HIGH HUMAN DEVELOPMENT
1,NORWAY,2,0.961,83.2339,18.185200,13.003630,64660.106220,6.0,1,VERY HIGH HUMAN DEVELOPMENT
2,ICELAND,3,0.959,82.6782,19.163059,13.767170,55782.049810,11.0,2,VERY HIGH HUMAN DEVELOPMENT
3,"HONG KONG, CHINA (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,6.0,4,VERY HIGH HUMAN DEVELOPMENT
4,AUSTRALIA,5,0.951,84.5265,21.054590,12.726820,49238.433350,18.0,5,VERY HIGH HUMAN DEVELOPMENT
...,...,...,...,...,...,...,...,...,...,...
186,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4.0,0,LOW HUMAN DEVELOPMENT
187,CENTRAL AFRICAN REPUBLIC,188,0.404,53.8947,8.040172,4.334000,966.058611,1.0,0,LOW HUMAN DEVELOPMENT
188,NIGER,189,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0,0,LOW HUMAN DEVELOPMENT
189,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,0,LOW HUMAN DEVELOPMENT
190,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1.0,0,LOW HUMAN DEVELOPMENT

## Parte 2

In [352]:
#Haciendo algunas prueba notamos que no siempre coinciden los cruces de "merge" por eso se realizo un diccionario para hacer los cambios
diccionario_cambios = {
    "HONG KONG, CHINA (SAR)": "CHINA",
    "NETHERLANDS": "NETHERLANDS (THE)",
    "UNITED KINGDOM": "UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN IRELAND (THE)",
    "KOREA (REPUBLIC OF)": "KOREA (THE REPUBLIC OF)",
    "UNITED STATES": "UNITED STATES MINOR OUTLYING ISLANDS (THE)",
    "UNITED ARAB EMIRATES": "UNITED ARAB EMIRATES (THE)",
    "TÃœRKIYE": "TURKEY",#
    "RUSSIAN FEDERATION": "RUSSIAN FEDERATION (THE)",
    "BAHAMAS": "BAHAMAS (THE)",
    "DOMINICAN REPUBLIC": "DOMINICAN REPUBLIC (THE)",
    "MOLDOVA (REPUBLIC OF)": "MOLDOVA (THE REPUBLIC OF)",
    "PHILIPPINES": "PHILIPPINES (THE)",
    "LAO PEOPLE'S DEMOCRATIC REPUBLIC": "LAO PEOPLE'S DEMOCRATIC REPUBLIC (THE)",
    "ESWATINI (KINGDOM OF)": "ESWATINI",
    "CONGO (DEMOCRATIC REPUBLIC OF THE)": "CONGO (THE DEMOCRATIC REPUBLIC OF THE)",
    "COMOROS": "COMOROS (THE)",
    "CÃ”TE D'IVOIRE": "CâˆšÃ®TE D'IVOIRE",#
    "TANZANIA (UNITED REPUBLIC OF)": "TANZANIA, THE UNITED REPUBLIC OF",
    "SUDAN": "SUDAN (THE)",
    "GAMBIA": "GAMBIA (THE)",
    "CONGO": "CONGO (THE)",
    "CENTRAL AFRICAN REPUBLIC": "CENTRAL AFRICAN REPUBLIC (THE)",
    "NIGER": "NIGER (THE)"
}

# Aplicar el mapeo al DataFrame
result['Country'] = result['Country'].replace(diccionario_cambios)

In [353]:
# Direccion que apunta directamente al archivo countryCODES.xlsx
countryCODES_path = append_data_path + "/countryCODES.xlsx"
countryCODES = pd.read_excel(countryCODES_path)

In [354]:
countryCODES

,Country,Officialstatename,InternetccTLD,iso2,iso3
0,AFGHANISTAN,The Islamic Republic of Afghanistan,.af,AF,AFG
1,ALBANIA,The Republic of Albania,.al,AL,ALB
2,ALGERIA,The People's Democratic Republic of Algeria,.dz,DZ,DZA
3,ANGOLA,The Republic of Angola,.ao,AO,AGO
4,ANTIGUA AND BARBUDA,Antigua and Barbuda,.ag,AG,ATG
...,...,...,...,...,...
166,UZBEKISTAN,The Republic of Uzbekistan,.uz,UZ,UZB
167,VIET NAM,The Socialist Republic of Viet Nam,.vn,VN,VNM
168,YEMEN,The Republic of Yemen,.ye,YE,YEM
169,ZAMBIA,The Republic of Zambia,.zm,ZM,ZMB
170,ZIMBABWE,The Republic of Zimbabwe,.zw,ZW,ZWE

In [355]:
#Realizamos el cruce en base a la columna "Country"
merged_df = pd.merge(result, countryCODES, on='Country', how='inner')
merged_df

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development,Officialstatename,InternetccTLD,iso2,iso3
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.859660,66933.004540,5.0,3,VERY HIGH HUMAN DEVELOPMENT,The Swiss Confederation,.ch,CH,CHE
1,NORWAY,2,0.961,83.2339,18.185200,13.003630,64660.106220,6.0,1,VERY HIGH HUMAN DEVELOPMENT,The Kingdom of Norway,.no,NO,NOR
2,ICELAND,3,0.959,82.6782,19.163059,13.767170,55782.049810,11.0,2,VERY HIGH HUMAN DEVELOPMENT,Iceland,.is,IS,ISL
3,CHINA,4,0.952,85.4734,17.278170,12.226210,62606.845400,6.0,4,VERY HIGH HUMAN DEVELOPMENT,The People's Republic of China,.cn,CN,CHN
4,CHINA,79,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82,HIGH HUMAN DEVELOPMENT,The People's Republic of China,.cn,CN,CHN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4.0,0,LOW HUMAN DEVELOPMENT,The Republic of Burundi,.bi,BI,BDI
168,CENTRAL AFRICAN REPUBLIC (THE),188,0.404,53.8947,8.040172,4.334000,966.058611,1.0,0,LOW HUMAN DEVELOPMENT,The Central African Republic,.cf,CF,CAF
169,NIGER (THE),189,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0,0,LOW HUMAN DEVELOPMENT,The Republic of the Niger,.ne,NE,NER
170,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,0,LOW HUMAN DEVELOPMENT,The Republic of Chad,.td,TD,TCD
171,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1.0,0,LOW HUMAN DEVELOPMENT,The Republic of South Sudan,.ss,SS,SSD

In [356]:
# Notamos que existe "China" tanto como pais como distrito distrito financiero en el merge y ahora le devolveremos su nombre anterior
condicion = (merged_df['Country'] == 'CHINA') & (merged_df['Hdi_Rank'] == 4)

# Cambiar el valor en la celda correspondiente
merged_df.loc[condicion, 'Country'] = 'HONG KONG, CHINA (SAR)' #Notamos que este es el distrito financiero
merged_df

,Country,Hdi_Rank,Human_Development_Index__2021,Life_Expectancy_At_Birth2021,Expected_Years_Of_Schooling2021,Mean_Years_Of_Schooling2021,Gross_National_Income__Per_Capita2021,Gni_Per_Capita_Rank_Minus_Hdi_Rank2021,Hdi_Rank2020,Development,Officialstatename,InternetccTLD,iso2,iso3
0,SWITZERLAND,1,0.962,83.9872,16.500299,13.859660,66933.004540,5.0,3,VERY HIGH HUMAN DEVELOPMENT,The Swiss Confederation,.ch,CH,CHE
1,NORWAY,2,0.961,83.2339,18.185200,13.003630,64660.106220,6.0,1,VERY HIGH HUMAN DEVELOPMENT,The Kingdom of Norway,.no,NO,NOR
2,ICELAND,3,0.959,82.6782,19.163059,13.767170,55782.049810,11.0,2,VERY HIGH HUMAN DEVELOPMENT,Iceland,.is,IS,ISL
3,"HONG KONG, CHINA (SAR)",4,0.952,85.4734,17.278170,12.226210,62606.845400,6.0,4,VERY HIGH HUMAN DEVELOPMENT,The People's Republic of China,.cn,CN,CHN
4,CHINA,79,0.768,78.2107,14.236115,7.600118,17504.399690,-8.0,82,HIGH HUMAN DEVELOPMENT,The People's Republic of China,.cn,CN,CHN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,BURUNDI,187,0.426,61.6627,10.722722,3.129267,731.786709,4.0,0,LOW HUMAN DEVELOPMENT,The Republic of Burundi,.bi,BI,BDI
168,CENTRAL AFRICAN REPUBLIC (THE),188,0.404,53.8947,8.040172,4.334000,966.058611,1.0,0,LOW HUMAN DEVELOPMENT,The Central African Republic,.cf,CF,CAF
169,NIGER (THE),189,0.400,61.5763,6.957112,2.116717,1239.866936,-3.0,0,LOW HUMAN DEVELOPMENT,The Republic of the Niger,.ne,NE,NER
170,CHAD,190,0.394,52.5254,8.035914,2.573774,1364.169417,-7.0,0,LOW HUMAN DEVELOPMENT,The Republic of Chad,.td,TD,TCD
171,SOUTH SUDAN,191,0.385,54.9752,5.542510,5.726140,767.787000,-1.0,0,LOW HUMAN DEVELOPMENT,The Republic of South Sudan,.ss,SS,SSD

## Parte 3

In [357]:
# Direccion que apunta directamente al archivo countryCODES.xlsx
fallecidos_path = append_data_path + "/fallecidosCOVID.csv"

In [358]:
#Leemos el archivo CSV en Pandas
fallecidos_df = pd.read_csv(fallecidos_path,sep=";")

In [359]:
fallecidos_df

,FECHA_CORTE,FECHA_FALLECIMIENTO,EDAD_DECLARADA,SEXO,CLASIFICACION_DEF,DEPARTAMENTO,PROVINCIA,DISTRITO,UBIGEO,UUID
0,20240317,20220219,63,MASCULINO,Criterio virolÃ³gico,TUMBES,TUMBES,TUMBES,240101.0,203506.0
1,20240317,20210529,74,MASCULINO,Criterio virolÃ³gico,TUMBES,TUMBES,TUMBES,240101.0,203532.0
2,20240317,20210623,72,FEMENINO,Criterio SINADEF,TACNA,TACNA,ALTO DE LA ALIANZA,230102.0,203584.0
3,20240317,20210824,85,MASCULINO,Criterio investigaciÃ³n EpidemiolÃ³gica,TUMBES,TUMBES,TUMBES,240101.0,212541.0
4,20240317,20210627,46,MASCULINO,Criterio virolÃ³gico,TACNA,TACNA,ALTO DE LA ALIANZA,230102.0,203665.0
...,...,...,...,...,...,...,...,...,...,...
220913,20240317,20200809,77,MASCULINO,Criterio radiolÃ³gico,AREQUIPA,AREQUIPA,ALTO SELVA ALEGRE,40102.0,NaN
220914,20240317,20201028,81,MASCULINO,Criterio clÃ­nico,LAMBAYEQUE,CHICLAYO,CHICLAYO,140101.0,NaN
220915,20240317,20200515,68,FEMENINO,Criterio SINADEF,LIMA,LIMA,LA MOLINA,150114.0,NaN
220916,20240317,20210414,66,FEMENINO,Criterio clÃ­nico,LIMA,LIMA,LOS OLIVOS,150117.0,NaN
220917,20240317,20200819,61,MASCULINO,Criterio nexo epidemiolÃ³gico,PIURA,PIURA,TAMBO GRANDE,200114.0,NaN

In [360]:
# Convertir FECHA_FALLECIMIENTO a datetime
fallecidos_df['FECHA_FALLECIMIENTO'] = pd.to_datetime(fallecidos_df['FECHA_FALLECIMIENTO'], format='%Y%m%d')

In [361]:
# Agrupamos por mes y aÃ±o, y contamos los fallecidos
fallecidos_df['AÃ±o-Mes'] = fallecidos_df['FECHA_FALLECIMIENTO'].dt.to_period('M')  # Crear una nueva columna para agrupar por mes y aÃ±o
reporte_mensual = fallecidos_df.groupby('AÃ±o-Mes').size().reset_index(name='Fallecidos')
reporte_mensual

    AÃ±o-Mes  Fallecidos
0   2020-03         181
1   2020-04        5134
2   2020-05       16363
3   2020-06       17462
4   2020-07       18501
5   2020-08       17668
6   2020-09        8437
7   2020-10        4471
8   2020-11        3229
9   2020-12        3885
10  2021-01       11175
11  2021-02       18645
12  2021-03       20691
13  2021-04       23110
14  2021-05       16692
15  2021-06        7722
16  2021-07        3481
17  2021-08        1850
18  2021-09        1140
19  2021-10        1066
20  2021-11        1107
21  2021-12        1283
22  2022-01        3562
23  2022-02        3503
24  2022-03        1299
25  2022-04         741
26  2022-05         625
27  2022-06         542
28  2022-07        1025
29  2022-08        1429
30  2022-09         892
31  2022-10         429
32  2022-11         272
33  2022-12         423
34  2023-01         371
35  2023-02         287
36  2023-03         295
37  2023-04         337
38  2023-05         323
39  2023-06         291
40  2023-07         258
41  2023-08         249
42  2023-09          60
43  2023-10          26
44  2023-11          33
45  2023-12          40
46  2024-01         249
47  2024-02          62
48  2024-03           2

## Parte 4

In [362]:
# Generar tabla pivote para hacer un reporte de fallecidos por mes con el tipo de muerte en columnas separadas
reporte_pivot = pd.pivot_table(fallecidos_df, 
                               index='AÃ±o-Mes', 
                               columns='CLASIFICACION_DEF', 
                               values='FECHA_CORTE', 
                               aggfunc='count', 
                               fill_value=0)

In [363]:
reporte_pivot

CLASIFICACION_DEF,Criterio SINADEF,Criterio clÃ­nico,Criterio investigaciÃ³n EpidemiolÃ³gica,Criterio nexo epidemiolÃ³gico,Criterio radiolÃ³gico,Criterio serolÃ³gico,Criterio virolÃ³gico,NotiCovid,sinadef
AÃ±o-Mes,,,,,,,,,
2020-03,35,52,25,2,7,2,58,0,0
2020-04,1793,541,498,68,182,778,1274,0,0
2020-05,6826,1152,1427,203,480,3233,3042,0,0
2020-06,5722,670,1706,251,391,5605,3117,0,0
2020-07,5012,609,1512,262,415,7501,3190,0,0
2020-08,4589,611,1456,208,534,7400,2870,0,0
2020-09,1984,475,755,105,233,3483,1402,0,0
2020-10,1091,463,469,50,172,1417,809,0,0
2020-11,704,462,307,37,186,867,666,0,0
2020-12,802,547,171,41,179,1047,1098,0,0
2021-01,2190,514,323,107,434,2448,5159,0,0
2021-02,4993,501,465,150,556,2539,9441,0,0
2021-03,6100,525,517,229,456,1703,11161,0,0
2021-04,7450,748,591,246,363,1488,12224,0,0
2021-05,5225,628,349,155,283,1175,8877,0,0
2021-06,2723,116,123,51,138,746,3825,0,0
2021-07,1025,113,67,35,68,521,1652,0,0
2021-08,578,75,22,15,36,287,837,0,0
2021-09,554,12,0,0,0,190,384,0,0
2021-10,469,12,0,0,0,148,437,0,0
2021-11,441,16,0,0,0,157,493,0,0
2021-12,585,8,0,0,0,133,557,0,0
2022-01,1894,22,0,0,0,41,1605,0,0
2022-02,1604,20,0,0,0,1,1878,0,0
2022-03,352,6,0,0,0,0,941,0,0
2022-04,131,9,0,0,0,0,601,0,0
2022-05,85,3,0,0,0,0,537,0,0
2022-06,81,3,0,0,0,0,458,0,0
2022-07,299,3,0,0,0,0,723,0,0
2022-08,405,6,0,0,0,0,1018,0,0
2022-09,154,12,0,0,0,0,726,0,0
2022-10,53,59,0,0,0,0,317,0,0
2022-11,23,0,0,0,0,0,249,0,0
2022-12,66,0,0,0,0,0,357,0,0
2023-01,34,1,0,0,0,0,336,0,0
2023-02,4,0,0,0,0,0,283,0,0
2023-03,6,0,0,0,0,0,289,0,0
2023-04,17,0,0,0,0,0,320,0,0
2023-05,6,0,0,0,0,0,317,0,0
2023-06,2,0,0,0,0,0,289,0,0
2023-07,3,0,0,0,0,0,255,0,0
2023-08,7,0,0,0,0,0,242,0,0
2023-09,7,0,0,0,0,0,53,0,0
2023-10,8,0,0,0,0,0,18,0,0
2023-11,13,0,0,0,0,0,20,0,0
2023-12,17,0,0,0,0,0,22,1,0
2024-01,35,0,0,0,0,0,83,115,16
2024-02,1,0,0,0,0,0,45,16,0
2024-03,0,0,0,0,0,0,2,0,0